import numpy as np
from manim import *
from copy import deepcopy

class Scenery(MovingCameraScene):
    def construct(self):
        # COLORS
        WHITE_G = color_gradient([WHITE, WHITE], 2)
        BLACK_G = color_gradient([BLACK, BLACK], 2)
        YEBLUE_G = color_gradient([ManimColor.from_hex("#FFED95"), ManimColor.from_hex("#16E3F9")], 200)
        YEW_G = color_gradient([ManimColor.from_hex("#FFBE81"), ManimColor.from_hex("#FFFFFF")], 200)
        BOOK_G = color_gradient([ManimColor.from_hex("#FFBE81"), ManimColor.from_hex("#BE722F")], 200)
        BOOK_G1 = color_gradient([ManimColor.from_hex("#ECA861"), ManimColor.from_hex("#C2772E")], 200)
        BOOK_G2 = color_gradient([ManimColor.from_hex("#FFBB76"), ManimColor.from_hex("#E09851")], 200)
        BOOK_G3 = color_gradient([ManimColor.from_hex("#FFBC75"), ManimColor.from_hex("#A45B17")], 200)
        BOOK_G4 = color_gradient([ManimColor.from_hex("#FFDCB3"), ManimColor.from_hex("#C86E19")], 200)
        BABY_G = color_gradient([ManimColor.from_hex("#FFBE81"), ManimColor.from_hex("#E8A15F")], 200)
        YELL_G = color_gradient([ManimColor.from_hex("#FEFE99"), ManimColor.from_hex("#FFC655")], 200)
        GREEN_G = color_gradient([ManimColor.from_hex("#BFFF97"), ManimColor.from_hex("#00C849")], 200)
        RED_G = color_gradient([ManimColor.from_hex("#FF7490"), ManimColor.from_hex("#FF0033")], 200)
        INK_G = color_gradient([ManimColor.from_hex("#713A13"), ManimColor.from_hex("#000000")], 200)

        # TEX TEMPLATE
        snsus_tex = TexTemplate(tex_compiler='lualatex')
        snsus_tex.add_to_preamble(r'\usepackage{pifont}')
        
        # SPECIFIC FUNCTIONS
        def TexGen(string, font_sz=50, col=WHITE_G, isMath=False, stroke_w=1.0, avgStrokeCol=True):
            if not isMath:
                if avgStrokeCol:
                    return Tex(fr'{string}', font_size=font_sz, tex_template=snsus_tex).set_color(col).set_stroke(color=average_color(col[0], col[-1]), width=stroke_w)
                else: return Tex(fr'{string}', font_size=font_sz, tex_template=snsus_tex).set_color(col).set_stroke(color=col, width=stroke_w)
            else:
                if avgStrokeCol:
                    return MathTex(fr'{string}', font_size=font_sz, tex_template=snsus_tex).set_color(col).set_stroke(color=average_color(col[0], col[-1]), width=stroke_w)
                else: return MathTex(fr'{string}', font_size=font_sz, tex_template=snsus_tex).set_color(col).set_stroke(color=col, width=stroke_w)
                
        def Draw(txt, stroke_w=2.0) -> Animation:
            draw_anims = []
            for t in txt:
                draw_anims.append(DrawBorderThenFill(t, stroke_color=t.get_stroke_colors(), stroke_width=stroke_w, run_time=1))
            return draw_anims
        
        def BounceIn(mobjects, run_t=0.5) -> Animation:
            bounce_anims = []
            for mob in mobjects:
                bounce_anims.append(GrowFromCenter(mob, rate_func=rate_functions.ease_out_back, run_time=run_t))
            return bounce_anims
        
        def PersonGen(txt):
            return VGroup(SVGMobject("person.svg", height=1, stroke_width=0), Circle(0.08, BLACK).set_stroke(color=BLACK).set_fill(color=BLACK, opacity=1).shift(0.24*UP+0.12*LEFT),
                          Circle(0.08, BLACK).set_stroke(color=BLACK).set_fill(color=BLACK, opacity=1).shift(0.24*UP+0.12*RIGHT), TexGen(rf'{txt}', col=WHITE_G, font_sz=31, stroke_w=1.8).shift(0.29*DOWN))
        
        def Dancer(d_l_arm, d_r_arm, d_l_leg, d_r_leg, shifting):
            person = PersonGen('.').shift(shifting)
            l_arm = FunctionGraph(lambda t: np.sin(t), x_range=[0, PI/10], color=WHITE_G).set_stroke(width=5).rotate(PI, about_point=ORIGIN).shift(0.2*DOWN+0.3*LEFT).shift(shifting)
            l_arm.add_updater(lambda mob: mob.become(FunctionGraph(lambda t: np.sin(t+d_l_arm.get_value())-np.sin(d_l_arm.get_value()), x_range=[0, PI/10], color=WHITE_G).set_stroke(width=5).rotate(PI, about_point=ORIGIN).shift(0.2*DOWN+0.3*LEFT).shift(shifting)))
            r_arm = FunctionGraph(lambda t: np.sin(t), x_range=[0, PI/10], color=WHITE_G).set_stroke(width=5).shift(0.2*DOWN+0.3*RIGHT).shift(shifting)
            r_arm.add_updater(lambda mob: mob.become(FunctionGraph(lambda t: np.sin(t+d_r_arm.get_value())-np.sin(d_r_arm.get_value()), x_range=[0, PI/10], color=WHITE_G).set_stroke(width=5).shift(0.2*DOWN+0.3*RIGHT).shift(shifting)))
            l_leg = FunctionGraph(lambda t: np.sin(t), x_range=[0, PI/6], color=WHITE_G).set_stroke(width=5).rotate(-PI/1.5, about_point=ORIGIN).shift(0.45*DOWN+0.1*LEFT).shift(shifting)
            l_leg.add_updater(lambda mob: mob.become(FunctionGraph(lambda t: np.sin(t+d_l_leg.get_value())-np.sin(d_l_leg.get_value()), x_range=[0, PI/6], color=WHITE_G).rotate(-PI/1.5, about_point=ORIGIN).set_stroke(width=5).shift(0.45*DOWN+0.1*LEFT).shift(shifting)))
            r_leg = FunctionGraph(lambda t: np.sin(t), x_range=[0, PI/6], color=WHITE_G).rotate(-PI/1.5, about_point=ORIGIN).set_stroke(width=5).shift(0.45*DOWN+0.1*RIGHT).shift(shifting)
            r_leg.add_updater(lambda mob: mob.become(FunctionGraph(lambda t: np.sin(t+d_r_leg.get_value())-np.sin(d_r_leg.get_value()), x_range=[0, PI/6], color=WHITE_G).rotate(-PI/1.5, about_point=ORIGIN).set_stroke(width=5).shift(0.45*DOWN+0.1*RIGHT).shift(shifting)))
            return VGroup(person, l_leg, r_leg, l_arm, r_arm)

        def CompCirc(point_A, point_B, end_col=WHITE_G):
            dot_A = Dot(point_A, radius=0.1).set_z_index(1).set_color(color=YELL_G[-1]).set_stroke(color=YELL_G[-1])
            dot_B = Dot(point_B, radius=0.1).set_z_index(0.9).set_color(color=YELL_G[0]).set_stroke(color=YELL_G[0])
            line_AB = Line(dot_A.get_center(), dot_B.get_center(), color=YELL_G).set_stroke(width=10, color=YELL_G).set_z_index(0.5)
            Circ = Circle(radius=line_AB.get_length()).rotate(line_AB.get_angle()).set_stroke(width=5, color=YELL_G).move_to(point_A)
            self.play(LaggedStart(BounceIn(dot_A), Create(line_AB), BounceIn(dot_B), lag_ratio=0.8))
            self.play(Rotate(dot_B, 2*PI, about_point=dot_A.get_center()), Create(Circ), Rotate(line_AB, 2*PI, about_point=dot_A.get_center()))
            self.play(Uncreate(line_AB), dot_B.animate.move_to(dot_A), run_time=0.7)
            self.remove(dot_B)
            self.play(Circ.animate.set_color(end_col).set_stroke(end_col), FadeOut(dot_A), run_time=0.7)
            return Circ
        
        def TrigAngGen(c_point1, c_point2, c_point3, pos):
            trig_l1 = Line(c_point1, c_point2)
            trig_l1_cp = Line(trig_l1.get_last_point(), trig_l1.get_start())
            trig_l2 = Line(trig_l1.get_last_point(), c_point3)
            trig_l2_cp = Line(trig_l2.get_last_point(), trig_l2.get_start())
            trig_l3 = Line(trig_l2.get_last_point(), trig_l1.get_start())
            trig_l3_cp = Line(trig_l3.get_last_point(), trig_l3.get_start())
            trig = VGroup(trig_l1, trig_l2, trig_l3).move_to(pos)
            trig_cp = VGroup(trig_l1_cp, trig_l2_cp, trig_l3_cp).move_to(pos)
            ang1_trig = Angle(trig_l1_cp, trig_l2, radius=0.55, other_angle=True)
            ang2_trig = Angle(trig_l2_cp, trig_l3, radius=0.55, other_angle=True)
            ang3_trig = Angle(trig_l3_cp, trig_l1, radius=0.55, other_angle=True)
            angles_trig = VGroup(ang1_trig, ang2_trig, ang3_trig)
            return trig, angles_trig

        def play_intro():
            b1 = Circle(0.5).set_fill(color=WHITE_G, opacity=1).set_stroke(color=WHITE_G)
            b2 = Circle(0.3).set_fill(color=WHITE_G, opacity=1).set_stroke(color=WHITE_G).next_to(b1, LEFT, buff=-0.3).shift(0.2*DOWN)
            b3 = Circle(0.2).set_fill(color=WHITE_G, opacity=1).set_stroke(color=WHITE_G).next_to(b2, UL, buff=-0.3)
            b4 = Circle(0.15).set_fill(color=WHITE_G, opacity=1).set_stroke(color=WHITE_G).next_to(b3, UL, buff=-0.2)
            b5 = Circle(0.1).set_fill(color=WHITE_G, opacity=1).set_stroke(color=WHITE_G).next_to(b4, UR, buff=-0.1).shift(0.15*LEFT)
            b6 = Circle(0.4).set_fill(color=WHITE_G, opacity=1).set_stroke(color=WHITE_G).stretch_to_fit_width(1.1).next_to(b2, LEFT, buff=-0.4).shift(0.2*DOWN).stretch_to_fit_height(0.6).set_z_index(-1)
            b7 = Circle(0.2).set_fill(color=WHITE_G, opacity=1).set_stroke(color=WHITE_G).next_to(b6, UL, buff=-0.3).shift(0.02*RIGHT+0.1*DOWN)
            b8 = Circle(0.2).set_fill(color=WHITE_G, opacity=1).set_stroke(color=WHITE_G).next_to(b7, RIGHT, buff=-0.3)
            b9 = Circle(0.2).set_fill(color=WHITE_G, opacity=1).set_stroke(color=WHITE_G).next_to(b8, UP, buff=-0.2)
            b10 = Circle(0.2).set_fill(color=WHITE_G, opacity=1).set_stroke(color=WHITE_G).next_to(b9, UR, buff=-0.37)
            b11 = Circle(0.16).set_fill(color=WHITE_G, opacity=1).set_stroke(color=WHITE_G).next_to(b10, UL, buff=-0.3)
            b12 = Circle(0.13).set_fill(color=WHITE_G, opacity=1).set_stroke(color=WHITE_G).next_to(b11, UL, buff=-0.2)
            b13 = Circle(0.1).set_fill(color=WHITE_G, opacity=1).set_stroke(color=WHITE_G).next_to(b12, UL, buff=-0.15)
            baby = VGroup(b1, b2, b3, b4, b5, b6, b7, b8, b9, b10, b11, b12, b13)
            euclid_up = SVGMobject('euclid_up.svg', height=5).set_color(YEW_G).set_stroke(color=WHITE_G).to_edge(UL, buff=1).shift(0.5*UP) 
            preg = SVGMobject('preg.svg', height=2.9, stroke_width=0.001).set_color(YEW_G).next_to(euclid_up, DOWN).shift(0.5*UP+0.777*RIGHT)
            nopreg = SVGMobject('nopreg.svg', height=2.9, stroke_width=0.1).set_color(YEW_G).move_to(preg).shift(0.43*LEFT)
            euclid = VGroup(euclid_up, preg, baby.next_to(preg, LEFT, buff=-0.7))
            baby.set_color(BABY_G)
            euclid.save_state()
            euclid.scale(1.71).to_edge(UL, buff=1).shift(0.5*UP)
            bc_300 = TexGen(r'300 BC').shift(3*UP)
            euclid_txt = TexGen(r'Euclid').next_to(bc_300, DOWN)
            bc_300.save_state()
            euclid_txt.save_state()
            bc_300.scale(2).shift(2*DOWN+4*RIGHT)
            euclid_txt.scale(2).next_to(bc_300, 2*DOWN) 
            self.play(DrawBorderThenFill(euclid, introducer=False, stroke_width=0.8, run_time=3), FadeIn(bc_300, euclid_txt, run_time=2))
            self.wait()
            self.play(Restore(euclid), Restore(bc_300), Restore(euclid_txt))
            self.wait()
            books.scale(0.8).next_to(preg, RIGHT)
            self.play(ReplacementTransform(preg, nopreg), LaggedStart(*(ReplacementTransform(baby[i], books[i]) for i in range(13))), run_time=2)
            self.wait()
            self.play(ReplacementTransform(books, elements.shift(1.2*DOWN), path_func=counterclockwise_path()), run_time=1.5)
            self.wait()
            timeline_hline = RoundedRectangle(0.02, width=12, height=0.04).set_fill(opacity=1, color=WHITE_G).rotate(PI)
            timeline_arup = RoundedRectangle(0.02, width=0.5, height=0.04).set_fill(opacity=1, color=WHITE_G).move_to(timeline_hline, aligned_edge=RIGHT).rotate(-PI/6, about_point=[6, 0, 0])
            timeline_ardw = RoundedRectangle(0.02, width=0.5, height=0.04).set_fill(opacity=1, color=WHITE_G).move_to(timeline_hline, aligned_edge=RIGHT).rotate(PI/6, about_point=[6, 0, 0])
            vline_300 = RoundedRectangle(0.02, width=0.5, height=0.04).set_fill(opacity=1, color=WHITE_G).rotate(PI/2, about_point=ORIGIN)
            timeline = VGroup(timeline_hline, timeline_arup, timeline_ardw, vline_300).shift(2.7*UP)
            inductive = TexGen(r'inductive').move_to([-3, 0, 0]).align_to(euclid_txt, 1.2*DOWN)
            ind_arr = TexGen(r'\Rightarrow', isMath=True, font_sz=100).move_to([-3, -1.2, 0])
            ded_arr = TexGen(r'\Rightarrow', isMath=True, font_sz=100).move_to([3, -1.2, 0])
            ded_arr_cp = deepcopy(ded_arr)
            deductive = TexGen(r'deductive').move_to([3, 0, 0]).align_to(euclid_txt, 1.2*DOWN)
            self.play(elements.animate.move_to(euclid_txt, aligned_edge=UP), ShrinkToCenter(euclid_txt), nopreg.animate.fade(darkness=1), euclid_up.animate.fade(darkness=1))
            self.play(LaggedStart(LaggedStart(Create(timeline[0:3]), GrowFromCenter(vline_300, run_time=0.8), lag_ratio=0.3), AnimationGroup(bc_300.animate.shift(0.3*UP), elements.animate.shift(0.3*DOWN), run_time=0.8), lag_ratio=0.2))
            self.wait()
            geo = Text("GEOMETRY", font="DIOGENES").next_to(elements, DOWN).set_color(BOOK_G).set_x(0)
            self.play(GrowFromPoint(geo, elements.get_center()-[0, 1, 0]))
            self.wait()
            outdated_line = RoundedRectangle(0.02, width=geo.width, height=0.04).set_fill(opacity=1, color=RED_G).set_stroke(color=RED_G).move_to(geo)
            outdated = TexGen(r'outdated', col=RED_G, font_sz=60).next_to(geo, DOWN)
            self.play(LaggedStart(Create(outdated_line), Draw(outdated), lag_ratio=0.7))
            self.wait()
            vline_19 = deepcopy(vline_300).shift(5*RIGHT)
            cent_19 = TexGen(r'19th').shift(3.3*UP).set_x(vline_19.get_x())
            hilberts_book.next_to(vline_19, DOWN).set_y(elements.get_y())
            self.play(GrowFromCenter(vline_19, run_time=0.8), FadeIn(cent_19, target_position=vline_19.get_center()), FadeIn(hilberts_book, target_position=hilberts_book.get_center()+[0, 0.7, 0]))
            self.wait()
            self.play(FadeOut(hilberts_book, vline_19, cent_19, outdated.set_z_index(1), outdated_line), geo.animate.fade(darkness=1))
            self.wait()
            self.play(Draw(inductive))
            self.wait()
            self.play(Draw(deductive))
            self.wait()
            self.play(elements.animate.scale(0.5).move_to(elements, aligned_edge=UP))
            friend_d_l_arm = ValueTracker(0)
            friend_d_r_arm = ValueTracker(0)
            friend_d_l_leg = ValueTracker(0)
            friend_d_r_leg = ValueTracker(0)
            friend_dancer = Dancer(friend_d_l_arm, friend_d_r_arm, friend_d_l_leg, friend_d_r_leg, shifting=4.5*LEFT+1*DOWN)
            f_cp_d_l_arm = ValueTracker(0)
            f_cp_d_r_arm = ValueTracker(0)
            f_cp_d_l_leg = ValueTracker(0)
            f_cp_d_r_leg = ValueTracker(0)
            f_cp_dancer = Dancer(f_cp_d_l_arm, f_cp_d_r_arm, f_cp_d_l_leg, f_cp_d_r_leg, shifting=4.5*RIGHT+1*DOWN)
            rnd1_d_l_arm = ValueTracker(0)
            rnd1_d_r_arm = ValueTracker(0)
            rnd1_d_l_leg = ValueTracker(0)
            rnd1_d_r_leg = ValueTracker(0)
            rnd1_dancer = Dancer(rnd1_d_l_arm, rnd1_d_r_arm, rnd1_d_l_leg, rnd1_d_r_leg, shifting=1.5*LEFT+1*DOWN)
            rnd2_d_l_arm = ValueTracker(0)
            rnd2_d_r_arm = ValueTracker(0)
            rnd2_d_l_leg = ValueTracker(0)
            rnd2_d_r_leg = ValueTracker(0)
            rnd2_dancer = Dancer(rnd2_d_l_arm, rnd2_d_r_arm, rnd2_d_l_leg, rnd2_d_r_leg, shifting=0.5*LEFT+1*DOWN)
            rnd3_d_l_arm = ValueTracker(0)
            rnd3_d_r_arm = ValueTracker(0)
            rnd3_d_l_leg = ValueTracker(0)
            rnd3_d_r_leg = ValueTracker(0)
            rnd3_dancer = Dancer(rnd3_d_l_arm, rnd3_d_r_arm, rnd3_d_l_leg, rnd3_d_r_leg, shifting=0.5*RIGHT+1*DOWN)
            rnd4_d_l_arm = ValueTracker(0)
            rnd4_d_r_arm = ValueTracker(0)
            rnd4_d_l_leg = ValueTracker(0)
            rnd4_d_r_leg = ValueTracker(0)
            rnd4_dancer = Dancer(rnd4_d_l_arm, rnd4_d_r_arm, rnd4_d_l_leg, rnd4_d_r_leg, shifting=1.5*RIGHT+1*DOWN)
            for bodypart in friend_dancer:
                bodypart.suspend_updating()
            self.play(GrowFromCenter(friend_dancer))
            self.play(Wiggle(friend_dancer, scale_value=1, rotation_angle=PI/10, n_wiggles=2, run_time=5), friend_d_l_leg.animate.set_value(5), friend_d_r_leg.animate.set_value(-10), friend_d_l_arm.animate.set_value(-10), friend_d_r_arm.animate.set_value(20), run_time=3)
            self.wait()
            self.play(Draw(ind_arr))
            for bodypart in rnd1_dancer, rnd2_dancer, rnd3_dancer, rnd4_dancer:
                bodypart.suspend_updating()
            self.play(GrowFromCenter(rnd1_dancer, point_color=BLACK), GrowFromCenter(rnd2_dancer, point_color=BLACK), GrowFromCenter(rnd3_dancer, point_color=BLACK), GrowFromCenter(rnd4_dancer, point_color=BLACK))
            self.play(Wiggle(rnd1_dancer, scale_value=1, rotation_angle=PI/10, n_wiggles=2, run_time=5), rnd1_d_l_leg.animate.set_value(-15), rnd1_d_r_leg.animate.set_value(12), rnd1_d_l_arm.animate.set_value(20), rnd1_d_r_arm.animate.set_value(-5),
                      Wiggle(rnd2_dancer, scale_value=1, rotation_angle=PI/9, n_wiggles=3, run_time=5), rnd2_d_l_leg.animate.set_value(-6), rnd2_d_r_leg.animate.set_value(-6), rnd2_d_l_arm.animate.set_value(-9), rnd2_d_r_arm.animate.set_value(20),
                      Wiggle(rnd3_dancer, scale_value=1, rotation_angle=PI/8, n_wiggles=1, run_time=5), rnd3_d_l_leg.animate.set_value(-20), rnd3_d_r_leg.animate.set_value(25), rnd3_d_l_arm.animate.set_value(-3), rnd3_d_r_arm.animate.set_value(13),
                      Wiggle(rnd4_dancer, scale_value=1, rotation_angle=PI/11, n_wiggles=2, run_time=5), rnd4_d_l_leg.animate.set_value(18), rnd4_d_r_leg.animate.set_value(-24), rnd4_d_l_arm.animate.set_value(17), rnd4_d_r_arm.animate.set_value(-22), run_time=3)
            black_rect = Rectangle(width=1.4, height=2.5).set_color(BLACK).set_stroke(color=BLACK).move_to(friend_dancer).set_fill(opacity=1, color=BLACK)
            inductive.save_state()
            self.wait()
            self.play(inductive.animate.next_to(ind_arr, 2.5*UP))
            self.wait()
            self.play(FadeOut(ind_arr), FadeIn(black_rect), Restore(inductive))
            self.wait()
            self.play(Wiggle(rnd1_dancer, scale_value=1, rotation_angle=PI/11, n_wiggles=2, run_time=5), rnd1_d_l_leg.animate.set_value(5), rnd1_d_r_leg.animate.set_value(19), rnd1_d_l_arm.animate.set_value(10), rnd1_d_r_arm.animate.set_value(0),
                      Wiggle(rnd2_dancer, scale_value=1, rotation_angle=PI/10, n_wiggles=1, run_time=5), rnd2_d_l_leg.animate.set_value(-31), rnd2_d_r_leg.animate.set_value(14), rnd2_d_l_arm.animate.set_value(-18), rnd2_d_r_arm.animate.set_value(11),
                      Wiggle(rnd3_dancer, scale_value=1, rotation_angle=PI/8, n_wiggles=2, run_time=5), rnd3_d_l_leg.animate.set_value(-9), rnd3_d_r_leg.animate.set_value(0), rnd3_d_l_arm.animate.set_value(13), rnd3_d_r_arm.animate.set_value(-1),
                      Wiggle(rnd4_dancer, scale_value=1, rotation_angle=PI/9, n_wiggles=3, run_time=5), rnd4_d_l_leg.animate.set_value(-14), rnd4_d_r_leg.animate.set_value(-37), rnd4_d_l_arm.animate.set_value(5), rnd4_d_r_arm.animate.set_value(-15), run_time=3)
            for bodypart in f_cp_dancer:
                bodypart.suspend_updating()
            self.play(Draw(ded_arr))
            self.play(GrowFromCenter(f_cp_dancer))
            self.play(Wiggle(f_cp_dancer, scale_value=1, rotation_angle=PI/10, n_wiggles=2, run_time=5), f_cp_d_l_leg.animate.set_value(5), f_cp_d_r_leg.animate.set_value(-10), f_cp_d_l_arm.animate.set_value(-10), f_cp_d_r_arm.animate.set_value(20), run_time=3)
            deductive.save_state()
            self.wait()
            self.play(deductive.animate.next_to(ded_arr, 2.5*UP))
            self.wait()
            black_rect2 = Rectangle(width=12, height=2.5).set_color(BLACK).set_stroke(color=BLACK).shift(DOWN*1.5).set_fill(opacity=1, color=BLACK)
            self.play(FadeIn(black_rect2), Restore(deductive))
            self.wait()
            ded_arr.fade(darkness=1)
            self.remove(friend_dancer, rnd1_dancer, rnd2_dancer, rnd3_dancer, rnd4_dancer, f_cp_dancer, ind_arr)
            self.remove(black_rect, black_rect2)
            trig, angles_trig = TrigAngGen([-1, -1, 0], [0.8, -1.2, 0], [-0.3, 1, 0], pos=friend_dancer)
            s1 = TexGen(r'1')
            s2 = TexGen(r'8').next_to(s1, buff=0.05)
            s3 = TexGen(r'0°').next_to(s2, buff=0.05)
            sum_180 = VGroup(s1, s2, s3).move_to(trig.get_center_of_mass()).shift(0.1*DOWN)
            self.play(Create(trig))
            self.play(Create(angles_trig[0]), Create(angles_trig[1]), Create(angles_trig[2]))
            self.play(ReplacementTransform(angles_trig[0], s3), ReplacementTransform(angles_trig[1], s2),ReplacementTransform(angles_trig[2], s1))
            self.wait()
            self.play(Draw(ind_arr), inductive.animate.next_to(ind_arr, 2.5*UP))
            trigs_1, angs_1 = TrigAngGen([-1, -0.8, 0], [0.2, 0, 0], [-0.4, 1.3, 0], pos=rnd1_dancer)
            trigs_2, angs_2 = TrigAngGen([0, 0, 0], [0.5, 0, 0], [0.5, 0.5, 0], pos=rnd2_dancer)
            trigs_3, angs_3 = TrigAngGen([0, 0, 0], [0.6, 0.2, 0], [0.6, 1.5, 0], pos=rnd3_dancer)
            trigs_4, angs_4 = TrigAngGen([0, 0, 0], [0.9, -0.6, 0], [0.2, -1.6, 0], pos=rnd4_dancer)
            trigs_1.shift(0.2*DOWN+0.1*LEFT)
            trigs_2.scale(2.3).rotate(-PI/2.2).shift(0.5*UP+0.1*RIGHT)
            trigs_3.scale(1.6).shift(0.1*UP+0.1*RIGHT)
            trigs_4.shift(0.25*RIGHT+0.2*DOWN)
            sum_trigs_1 = TexGen(r'180°', font_sz=27).move_to(trigs_1.get_center_of_mass()).shift(0.1*RIGHT)
            sum_trigs_2 = TexGen(r'180°', font_sz=27).move_to(trigs_2.get_center_of_mass()).shift(0.1*DOWN)
            sum_trigs_3 = TexGen(r'180°', font_sz=27).move_to(trigs_3.get_center_of_mass()).shift(0.25*DOWN)
            sum_trigs_4 = TexGen(r'180°', font_sz=27).move_to(trigs_4.get_center_of_mass()).shift(0.05*RIGHT+0.05*UP)
            self.play(LaggedStart(AnimationGroup(Create(trigs_1), Create(trigs_2), Create(trigs_3), Create(trigs_4)), FadeIn(sum_trigs_1, sum_trigs_2, sum_trigs_3, sum_trigs_4), lag_ratio=0.6))
            self.wait()
            self.play(Restore(inductive), FadeOut(sum_180, trig, ind_arr, sum_trigs_1, sum_trigs_2, sum_trigs_3, sum_trigs_4))
            what = TexGen(r'What are triangles?').to_edge(DOWN, buff=0.6)
            how = TexGen(r'How to cunstruct them?').move_to(what).align_to(what, UP)
            prop = TexGen(r'What properties do they have?').move_to(what).align_to(what, UP)
            self.wait()
            self.play(Draw(what))
            self.wait()
            self.play(ReplacementTransform(what, how))
            self.wait()
            self.play(ReplacementTransform(how, prop))
            self.wait()
            VGroup(trig, sum_180).move_to(f_cp_dancer).shift(0.2*RIGHT)
            self.play(FadeOut(prop))
            self.play(Draw(ded_arr_cp), deductive.animate.next_to(ded_arr_cp, 2.5*UP))
            self.play(LaggedStart(Create(trig), FadeIn(sum_180), lag_ratio=0.6))
            self.wait()
            self.play(FadeOut(trigs_1, trigs_2, trigs_3, trigs_4, ded_arr_cp, trig, sum_180), Restore(deductive))
            self.wait()
            defs = Text("Definitions", font="DIOGENES").next_to(elements, DOWN).set_color(BOOK_G)
            axs = Text("Axioms/Postulates", font="DIOGENES").next_to(defs, DOWN).set_color(BOOK_G)
            theos = Text("Theorems/Propositions", font="DIOGENES").next_to(axs, DOWN).set_color(BOOK_G)
            self.play(GrowFromPoint(defs, elements.get_center()-[0, 0.5, 0]))
            self.wait()
            self.play(GrowFromPoint(axs, elements.get_center()-[0, 0.4, 0]))
            self.wait()
            self.play(GrowFromPoint(theos, elements.get_center()-[0, 0.3, 0]))
            self.wait()
            self.play(FadeOut(bc_300, inductive, deductive, timeline, elements, axs, theos), defs.animate.scale(1.2))
            meaning = TexGen(r'$\widehat{=}$ meaning of words/phrases').next_to(defs, DOWN)
            self.wait()
            self.play(Draw(meaning))
            self.wait()
            self.play(FadeOut(meaning, defs))

        def play_def_in():
            self.play(LaggedStart(*def_anims, lag_ratio=0.95, run_time=3, rate_func=rate_functions.ease_in_out_expo))

        def play_def_1():
            self.add(def_G.shift(7*RIGHT).scale(1/1.5))
            self.wait()
            self.play(Draw(D1))
            self.play(Create(uline_D1))
            q = TexGen(r'?', font_sz=200).move_to(canv_center)
            self.wait()
            self.play(BounceIn(q))
            self.wait()
            self.play(q.animate.scale(1.8), rate_func=rate_functions.ease_out_back, run_time=0.5)
            self.wait()
            self.play(q.animate.scale(1.8), rate_func=rate_functions.ease_out_back, run_time=0.5)
            dot = Dot(q.get_center()+[-0.085, -2.02, 0], 0.37).set_color(BOOK_G).set_stroke(color=BOOK_G)
            self.wait()
            self.play(FadeOut(q), FadeIn(dot))
            self.wait()
            self.play(dot.animate.scale(0))
            self.wait()
            self.play(Rotate(Group(def_G[22], D1, uline_D1), -PI/1.5, about_point=[-8, 5, 0], axis=UP))

        def play_def_2_4():
            self.add(def_G[:-1].shift(7*RIGHT).scale(1/1.5))
            self.play(Draw(D2))
            self.play(Create(uline_D2))
            self.wait()
            l1 = FunctionGraph(function=lambda x: np.sin(x), x_range=[-0.2, 0.6*PI]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=11).stretch_to_fit_width(6.4).move_to(canv_center)
            l2 = FunctionGraph(function=lambda x: x**3+2*x**2+x, x_range=[-1.5, 1]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=11).stretch_to_fit_width(5).rotate(-PI/3.1, about_point=canv_center).move_to(canv_center)
            self.play(Create(l1))
            self.wait()
            self.play(ReplacementTransform(l1, l2))
            self.wait()
            l2.save_state()
            self.play(l2.animate.set_stroke(width=0), run_time=1.7)
            self.wait()
            self.play(Restore(l2))
            self.wait()
            dot1 = Dot(l2.get_start(), 0.12).set_color(BOOK_G).set_stroke(color=BOOK_G)
            dot2 = Dot(l2.get_last_point(), 0.12).set_color(BOOK_G).set_stroke(color=BOOK_G)
            self.play(l2.animate.set_color(WHITE_G).set_stroke(color=WHITE_G, width=11), Rotate(Group(def_G[21], D2, uline_D2), -PI/1.5, about_point=[-8, 5, 0], axis=UP))
            self.play(Draw(D3))
            self.wait()
            self.play(Draw([dot1, dot2]))
            self.wait()
            l3 = Line(start=l2.get_start(), end=l2.get_last_point()).set_color(BOOK_G).set_stroke(color=BOOK_G, width=11)
            self.play(dot1.animate.set_color(WHITE_G).set_stroke(color=WHITE_G), dot2.animate.set_color(WHITE_G).set_stroke(color=WHITE_G),Rotate(Group(def_G[20], D3), -PI/1.5, about_point=[-8, 5, 0], axis=UP))
            self.play(Draw(D4))
            self.play(Create(uline_D4))
            self.wait()
            self.play(ReplacementTransform(l2, l3))
            self.play(Rotate(Group(def_G[19], D4, uline_D4), -PI/1.5, about_point=[-8, 5, 0], axis=UP), dot1.animate.fade(darkness=1), dot2.animate.fade(darkness=1), l3.animate.fade(darkness=1))

        def play_def_5_7():
            self.add(def_G[:-4].shift(7*RIGHT).scale(1/1.5))
            self.play(Draw(D5))
            self.play(Create(uline_D5))
            surf1 = FunctionGraph(function=lambda x: np.sin(x), x_range=[-0.9, 0.55*PI]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=5).stretch_to_fit_width(4).move_to(canv_center)
            curved_lines_surf1 = FunctionGraph(function=lambda x: np.sin(x), x_range=[-0.9, 0.55*PI]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=312).stretch_to_fit_width(4).move_to(canv_center).set_z_index(-1)
            bottom_line_surf1 = Line(start=[-0.059, 0.55, 0], end=[1.09, -2.335, 0]).set_stroke(width=8, color=BOOK_G1)
            top_line_surf1 = Line(start=[4.65, 2.433, 0], end=[4.35, -0.672, 0]).set_stroke(width=8, color=BOOK_G2)
            surf2 = FunctionGraph(function=lambda x: x, x_range=[-0.9, 0.55*PI]).set_color(WHITE_G).set_stroke(color=WHITE_G, width=330).stretch_to_fit_width(4).rotate(PI/2).move_to(canv_center)
            curved_lines_surf2 = FunctionGraph(function=lambda x: x, x_range=[-0.9, 0.55*PI]).set_stroke(color=BOOK_G, width=345).stretch_to_fit_width(4).rotate(PI/2).move_to(canv_center).set_z_index(-1)
            top_line_surf2 = Line(start=[-0.251, 1.05, 0], end=[2.625, 2.95, 0])
            bottom_line_surf2 = Line(start=[2.375, -2.95, 0], end=[5.25, -1.05, 0])
            VGroup(surf1, curved_lines_surf1, bottom_line_surf1, top_line_surf1).rotate(PI*0.61).move_to(canv_center)
            self.play(Create(surf1))
            self.wait(0.2)
            self.play(surf1.animate.set_stroke(width=300))
            self.wait()
            self.play(Rotate(Group(def_G[18], D5, uline_D5), -PI/1.5, about_point=[-8, 5, 0], axis=UP), surf1.animate.set_color(WHITE_G).set_stroke(color=WHITE_G))
            self.play(Draw(D6))
            self.wait()
            self.play(LaggedStart(AnimationGroup(surf1.animate.set_stroke(width=297), Create(curved_lines_surf1)), AnimationGroup(Create(bottom_line_surf1), Create(top_line_surf1)), lag_ratio=0.9))
            self.play(Rotate(Group(def_G[17], D6), -PI/1.5, about_point=[-8, 5, 0], axis=UP))
            self.play(Draw(D7))
            self.play(Create(uline_D7))
            self.play(ReplacementTransform(surf1, surf2), ReplacementTransform(curved_lines_surf1, curved_lines_surf2), ReplacementTransform(bottom_line_surf1, bottom_line_surf2.set_stroke(width=8, color=BOOK_G3)), ReplacementTransform(top_line_surf1, top_line_surf2.set_stroke(width=8, color=BOOK_G4)), run_time=2)
            self.wait()
            self.play(Rotate(Group(def_G[16], D7, uline_D7), -PI/1.5, about_point=[-8, 5, 0], axis=UP), FadeOut(surf2, curved_lines_surf2, top_line_surf2, bottom_line_surf2))
            
        def play_def_8_12():
            self.add(def_G[:-7].shift(7*RIGHT).scale(1/1.5))
            self.play(Draw(D8))
            self.play(Create(uline_D8))
            self.wait()
            l1_curv = FunctionGraph(function=lambda x: x**2, x_range=[0.5, 2]).set_color(WHITE_G).set_stroke(color=WHITE_G, width=10).rotate(-0.38*PI).stretch_to_fit_width(5).move_to(canv_center).shift(0.1*DOWN)
            l2_curv = FunctionGraph(function=lambda x: np.sin(x), x_range=[0, 1.8]).set_color(WHITE_G).set_stroke(color=WHITE_G, width=10).stretch_to_fit_width(7).rotate(0.2*PI).move_to(canv_center)
            l1_st = Line(start=ORIGIN, end=[5, 0, 0]).set_stroke(color=WHITE_G, width=10)
            l2_st = Line(start=l2_curv.get_start(), end=l2_curv.get_last_point()).set_stroke(color=WHITE_G, width=10)
            a2 = Angle(l1_st, l2_st, radius=2).set_stroke(color=BOOK_G, width=10).set_z_index(-1)
            a1 = deepcopy(a2).shift(0.6*LEFT+0.15*DOWN).scale(0.98).set_z_index(-1)
            self.play(Create(l1_curv), Create(l2_curv))
            self.wait()
            self.play(Create(a1))
            self.wait()
            self.play(Rotate(Group(def_G[15], D8, uline_D8), -PI/1.5, about_point=[-8, 5, 0], axis=UP))
            self.play(Draw(D9))
            self.wait()
            self.play(Create(uline_D9))
            self.play(ReplacementTransform(l1_curv, l1_st), ReplacementTransform(l2_curv, l2_st), ReplacementTransform(a1, a2))
            a2.add_updater(lambda mob: mob.become(Angle(l1_st, l2_st, radius=2).set_stroke(color=BOOK_G, width=10).set_z_index(-1)))
            self.play(Rotate(Group(def_G[14], D9, uline_D9), -PI/1.5, about_point=[-8, 5, 0], axis=UP))
            self.play(Draw(D10))
            self.wait()
            self.play(Create(uline1_D10))
            self.wait()
            self.play(Create(uline2_D10))
            self.wait()
            a2_op = Angle(Line(l1_st.get_last_point(), l1_st.get_start()), l2_st, radius=2, other_angle=True).set_stroke(color=WHITE_G, width=10).set_z_index(-1)
            a2_op.add_updater(lambda mob: mob.become(Angle(Line(l1_st.get_last_point(), l1_st.get_start()), l2_st, radius=2, other_angle=True).set_stroke(color=WHITE_G, width=10).set_z_index(-1)))
            self.play(Create(a2_op))
            self.wait()
            self.play(LaggedStart(Rotate(l2_st, angle=PI/2-a2.get_value(), about_point=[2.5, 0, 0]), Flash([2.5, 2, 0], color=BOOK_G, time_width=0.5), lag_ratio=0.6))
            self.wait()
            a2_op.clear_updaters()
            self.play(Rotate(Group(def_G[13], D10, uline2_D10, uline1_D10), -PI/1.5, about_point=[-8, 5, 0], axis=UP), a2_op.animate.fade(darkness=1))
            self.play(Draw(D11))
            self.play(Create(uline_D11))
            self.play(Rotate(l2_st, angle=PI/4, about_point=[2.5, 0, 0]))
            self.play(Rotate(Group(def_G[12], D11, uline_D11), -PI/1.5, about_point=[-8, 5, 0], axis=UP))
            self.play(Draw(D12))
            self.play(Create(uline_D12))
            self.play(Rotate(l2_st, angle=-PI/2, about_point=[2.5, 0, 0]))
            a2.clear_updaters()
            self.play(Rotate(Group(def_G[11], D12, uline_D12), -PI/1.5, about_point=[-8, 5, 0], axis=UP), FadeOut(l2_st, a2, l1_st))
            
        def play_def_13_14():
            self.add(def_G[:-12].shift(7*RIGHT).scale(1/1.5))
            self.play(Draw(D13))
            self.play(Create(uline_D13))
            line = FunctionGraph(function=lambda x: 0, x_range=[0, 4]).move_to(canv_center).set_color(WHITE_G).set_stroke(color=WHITE_G, width=10)
            d1 = Dot(line.get_start(), 0.12).set_color(WHITE_G).set_stroke(color=WHITE_G).rotate(PI)
            d2 = Dot(line.get_last_point(), 0.12).set_color(WHITE_G).set_stroke(color=WHITE_G)
            self.wait()
            self.play(Create(line))
            self.wait()
            self.play(Create(d1), Create(d2))
            self.wait()
            l_top = deepcopy(line).rotate(PI).shift(2*UP).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).set_z_index(1).stretch_to_fit_width(4.1)
            l_bottom = deepcopy(line).shift(2*DOWN).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).set_z_index(1).stretch_to_fit_width(4.1)
            l_left = deepcopy(line).rotate(PI/2).move_to([0.5, 0, 0]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).set_z_index(1)
            l_right = deepcopy(line).rotate(-PI/2).move_to([4.5, 0, 0]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).set_z_index(1)
            self.play(d1.animate.set_color(BOOK_G).set_stroke(BOOK_G), d2.animate.set_color(BOOK_G).set_stroke(BOOK_G))
            self.play(line.animate.set_stroke(width=400), ReplacementTransform(d1, VGroup(l_left, l_bottom)), ReplacementTransform(d2, VGroup(l_right, l_top)))
            self.wait()
            sq = Square(4).set_color(WHITE_G).set_stroke(color=WHITE_G).set_fill(color=WHITE_G, opacity=1).move_to(canv_center)
            self.add(sq)
            self.remove(line)
            cube = Cube(4, fill_color=BOOK_G, stroke_width=2).rotate(-0.2*PI, axis=UP).rotate(0.1*PI, axis=RIGHT).move_to(canv_center).set_stroke(color=WHITE_G)
            sq_cube = VGroup(sq, l_left, l_right, l_top, l_bottom)
            self.play(sq_cube.animate.become(cube), run_time=2)
            self.play(Rotate(sq_cube, angle=PI/4, axis=UP, run_time=3))
            self.play(Rotate(Group(def_G[10], D13, uline_D13), -PI/1.5, about_point=[-8, 5, 0], axis=UP))
            self.play(Draw(D14))
            self.play(Create(uline_D14))
            self.wait()
            self.play(Rotate(Group(def_G[9], D14, uline_D14), -PI/1.5, about_point=[-8, 5, 0], axis=UP), FadeOut(sq_cube))

        def play_def_15_18():
            self.add(def_G[:-14].shift(7*RIGHT).scale(1/1.5))
            self.play(Draw(D15))
            self.play(Create(uline_D15))  
            self.wait()  
            elps = Ellipse(5.5, 3).set_color(WHITE_G).set_stroke(color=WHITE_G, width=10).rotate(0.2*PI).move_to(canv_center).set_z_index(1)
            circ = Circle(2.5).set_fill(WHITE_G, opacity=0.3).set_color(WHITE_G).set_stroke(color=WHITE_G, width=10).rotate(0.2*PI).move_to(canv_center).set_z_index(1)
            self.play(Create(elps))
            self.play(elps.animate.set_fill(WHITE_G, opacity=0.3))
            points_on_elps = [elps.point_at_angle(2 * PI * i / 10) for i in range(10)]
            dots_on_elps = VGroup(*[Dot(point, 0.01) for point in points_on_elps])
            points_on_circ = [circ.point_at_angle(2 * PI * i / 10) for i in range(10)]
            dots_on_circ = VGroup(*[Dot(point, 0.01) for point in points_on_circ])
            mov_point = Dot([1.5, -1, 0], 0.15).set_stroke(color=WHITE_G).set_color(WHITE_G).set_z_index(1)
            lines = VGroup()
            for i in range(10):
                lines.add(Line(mov_point.get_center(), dots_on_elps[i].get_center()).set_stroke(color=RED_G, width=6))
            lines[0].add_updater(lambda mob: mob.become(Line(mov_point.get_center(), dots_on_elps[0].get_center()).set_stroke(color=RED_G, width=6)))
            lines[1].add_updater(lambda mob: mob.become(Line(mov_point.get_center(), dots_on_elps[1].get_center()).set_stroke(color=RED_G, width=6)))
            lines[2].add_updater(lambda mob: mob.become(Line(mov_point.get_center(), dots_on_elps[2].get_center()).set_stroke(color=RED_G, width=6)))
            lines[3].add_updater(lambda mob: mob.become(Line(mov_point.get_center(), dots_on_elps[3].get_center()).set_stroke(color=RED_G, width=6)))
            lines[4].add_updater(lambda mob: mob.become(Line(mov_point.get_center(), dots_on_elps[4].get_center()).set_stroke(color=RED_G, width=6)))
            lines[5].add_updater(lambda mob: mob.become(Line(mov_point.get_center(), dots_on_elps[5].get_center()).set_stroke(color=RED_G, width=6)))
            lines[6].add_updater(lambda mob: mob.become(Line(mov_point.get_center(), dots_on_elps[6].get_center()).set_stroke(color=RED_G, width=6)))
            lines[7].add_updater(lambda mob: mob.become(Line(mov_point.get_center(), dots_on_elps[7].get_center()).set_stroke(color=RED_G, width=6)))
            lines[8].add_updater(lambda mob: mob.become(Line(mov_point.get_center(), dots_on_elps[8].get_center()).set_stroke(color=RED_G, width=6)))
            lines[9].add_updater(lambda mob: mob.become(Line(mov_point.get_center(), dots_on_elps[9].get_center()).set_stroke(color=RED_G, width=6)))
            self.wait()
            self.play(Create(mov_point))
            self.play(Create(lines), run_time=1)
            self.wait()
            self.play(mov_point.animate.move_to([4, 0, 0]))
            self.play(mov_point.animate.move_to(circ.get_center()))
            self.wait()
            for line in lines:
                line.clear_updaters()
            self.play(LaggedStart(AnimationGroup(elps.animate.become(circ), *[dots_on_elps[i].animate.become(dots_on_circ[i]) for i in range(10)], *[lines[i].animate.put_start_and_end_on(mov_point.get_center(), dots_on_circ[i].get_center()).set_stroke(color=GREEN_G) for i in range(10)]), Flash(canv_center, color=BOOK_G, time_width=0.5), lag_ratio=0.4))
            self.play(FadeOut(lines, mov_point), elps.animate.set_fill(BOOK_G, opacity=0.3))
            self.remove(*dots_on_elps)
            self.wait()
            self.play(elps.animate.set_fill(opacity=0))
            self.play(Rotate(Group(def_G[8], D15, uline_D15), -PI/1.5, about_point=[-8, 5, 0], axis=UP))
            self.play(Draw(D16))
            self.play(BounceIn(mov_point.set_color(BOOK_G).set_stroke(BOOK_G).set_z_index(2)))
            self.wait()
            self.play(Create(uline_D16))
            diam = Line([-0.05, 0, 0], [5.05, 0, 0]).set_stroke(color=BOOK_G, width=10).rotate(0.2*PI, about_point=canv_center)
            self.play(Rotate(Group(def_G[7], D16, uline_D16), -PI/1.5, about_point=[-8, 5, 0], axis=UP), mov_point.animate.set_color(WHITE_G).set_stroke(WHITE_G))
            self.play(Draw(D17))
            self.play(Create(uline_D17))
            self.wait()
            self.play(Create(diam))
            semi = Arc(2.5, start_angle=0, angle=PI, arc_center=canv_center).set_color(WHITE_G).set_stroke(color=WHITE_G, width=10).rotate(0.2*PI, about_point=canv_center).set_z_index(1)
            semi_half1 = Arc(2.5, start_angle=0, angle=PI/2, arc_center=canv_center).set_color(WHITE_G).set_stroke(color=WHITE_G, width=10).flip(about_point=canv_center).rotate(0.2*PI+PI/2, about_point=canv_center).set_z_index(1)
            semi_half2 = Arc(2.5, start_angle=0, angle=PI/2, arc_center=canv_center).set_color(WHITE_G).set_stroke(color=WHITE_G, width=10).rotate(0.2*PI-PI/2, about_point=canv_center).set_z_index(1)
            self.add(semi, semi_half1, semi_half2)
            self.remove(elps)
            self.wait()
            self.play(Rotate(Group(def_G[6], D17, uline_D17), -PI/1.5, about_point=[-8, 5, 0], axis=UP))
            self.play(Draw(D18))
            self.play(Create(uline_D18))
            self.wait()
            self.play(LaggedStart(ScaleInPlace(diam.set_z_index(1.5), scale_factor=1.3, rate_func=rate_functions.there_and_back), AnimationGroup(Uncreate(semi_half1), Uncreate(semi_half2)), semi.animate.set_stroke(color=BOOK_G), lag_ratio=0.1))
            self.wait()
            self.play(VGroup(semi, diam).animate.set_stroke(color=WHITE_G), mov_point.animate.set_color(BOOK_G).set_stroke(color=BOOK_G))
            self.play(Rotate(Group(def_G[5], D18, uline_D18), -PI/1.5, about_point=[-8, 5, 0], axis=UP), FadeOut(semi, diam, mov_point))

        def play_def_19():
            self.add(def_G[:-18].shift(7*RIGHT).scale(1/1.5))
            self.play(Draw(D19_1))
            self.play(Create(uline_D19_1))
            self.wait()  
            self.play(Draw(D19_2))
            self.play(Create(uline_D19_2))
            trig = Polygon(ORIGIN, [5, 0, 0], [4, 4, 0]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).move_to(canv_center)
            self.play(Create(trig))
            self.wait()
            rect = Polygon(ORIGIN, [5, 0, 0], [4, 4, 0], [1, 2, 0]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).move_to(canv_center)
            self.play(ReplacementTransform(D19_2, D19_3), ReplacementTransform(uline_D19_2, uline_D19_3))
            self.play(ReplacementTransform(trig, rect))
            self.wait()
            pent = Polygon(ORIGIN, [5, 0, 0], [4, 4, 0], [2.5, 1, 0], [1, 2, 0]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).move_to(canv_center)
            self.play(ReplacementTransform(D19_3, D19_4), ReplacementTransform(uline_D19_3, uline_D19_4))
            self.play(ReplacementTransform(rect, pent))
            self.wait()
            self.play(Rotate(Group(def_G[4], D19_1, uline_D19_1, D19_4, uline_D19_4), -PI/1.5, about_point=[-8, 5, 0], axis=UP), FadeOut(pent))
            
        def play_def_20_21():
            self.add(def_G[:-19].shift(7*RIGHT).scale(1/1.5))
            self.play(Draw(D20_1))
            self.wait()
            self.play(Create(uline_D20_1))
            self.wait()  
            ang_corner = [4.5, -3, 0]
            eq_trig = Polygon(ORIGIN, [4, 0, 0], [2, np.sqrt(3)*2, 0]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).move_to(canv_center)
            iso_trig = Polygon(ORIGIN, [4, 0, 0], [2, 6, 0]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).move_to(canv_center)
            ac_trig = deepcopy(iso_trig)
            scl_trig = Polygon(ORIGIN, [4, 0, 0], [5.5, 6, 0]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).move_to(canv_center).shift(1.5/2*RIGHT)
            ob_trig = deepcopy(scl_trig)
            right_trig = Polygon(ORIGIN, [4, 0, 0], [4, 6, 0]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).move_to(canv_center)
            l1 = Line(ang_corner, [4.5, 3, 0]).set_stroke(BLACK, width=0).set_z_index(-1)
            l2 = Line(ang_corner, [0.5, -3, 0])
            ang = Angle(l1, l2, radius=1.5).set_stroke(color=WHITE_G, width=10).set_z_index(-1)
            ang.add_updater(lambda mob: mob.become(Angle(l1, l2, radius=1.5).set_stroke(color=WHITE_G, width=10).set_z_index(-1)))
            ang2 = Angle(Line([0.5, -3, 0], ang_corner), Line([0.5, -3, 0], [2.5, 3, 0]), 1.5).set_stroke(color=WHITE_G, width=10).set_z_index(-1)
            ang3 = Angle(Line([2.5, 3, 0], [0.5, -3, 0]), Line([2.5, 3, 0], ang_corner), 1.5).set_stroke(color=WHITE_G, width=10).set_z_index(-1)
            self.play(Create(eq_trig))
            self.wait()
            self.play(Draw(D20_2))
            self.play(Create(uline_D20_2))
            self.play(ReplacementTransform(eq_trig, iso_trig))
            self.wait()
            self.play(ReplacementTransform(D20_2, D20_3), ReplacementTransform(uline_D20_2, uline_D20_3))
            self.play(ReplacementTransform(iso_trig, scl_trig))
            self.wait()
            self.play(Rotate(Group(def_G[3], D20_3, uline_D20_3, D20_1, uline_D20_1), -PI/1.5, about_point=[-8, 5, 0], axis=UP))
            self.play(Draw(D21_1))
            self.wait()
            self.play(Create(uline_D21_1))
            self.play(ReplacementTransform(scl_trig, right_trig))
            self.play(Create(ang))
            self.play(Draw(D21_2))
            self.play(Create(uline_D21_2))
            self.play(ReplacementTransform(right_trig, ob_trig), l1.animate.become(Line(ang_corner, [6, 3, 0]).set_stroke(BLACK, width=0).set_z_index(-1)))
            self.wait()
            self.play(ReplacementTransform(D21_2, D21_3), ReplacementTransform(uline_D21_2, uline_D21_3))
            self.play(ReplacementTransform(ob_trig, ac_trig), l1.animate.become(Line(ang_corner, [2.5, 3, 0]).set_stroke(BLACK, width=0).set_z_index(-1)))
            self.play(Create(ang2), Create(ang3))
            ang.clear_updaters()
            self.wait()
            self.play(Rotate(Group(def_G[2], D21_3, uline_D21_3, D21_1, uline_D21_1), -PI/1.5, about_point=[-8, 5, 0], axis=UP), FadeOut(ang2, ang3, ang, ac_trig))

        def play_def_22():
            self.add(def_G[:-21].shift(7*RIGHT).scale(1/1.5))
            self.play(Draw(D22_1))
            self.wait()
            self.play(Create(uline_D22_1))
            self.wait()
            sq = Square(4).set_stroke(BOOK_G, width=10).move_to(canv_center)
            rhomb = Polygon([1, 0, 0], [2, 2, 0], [1, 4, 0], [0, 2, 0]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).move_to(canv_center).rotate(PI, about_point=canv_center).scale(1.5)
            pgram = Polygon([0, 0, 0], [5, 0, 0], [6, 2.5, 0], [1, 2.5, 0]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).move_to(canv_center).rotate(PI, about_point=canv_center)
            trpz = Polygon([3, 0, 0], [5, 0, 0], [6, 2.5, 0], [1, 2.5, 0]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=10).move_to(canv_center).rotate(PI, about_point=canv_center)
            self.play(Create(sq))
            self.wait()
            self.play(Draw(D22_2))
            self.play(Create(uline_D22_2))
            self.play(sq.animate.stretch_to_fit_height(2.5))
            self.wait()
            self.play(ReplacementTransform(D22_2, D22_3), ReplacementTransform(uline_D22_2, uline_D22_3))
            self.play(ReplacementTransform(sq, rhomb))
            self.wait()
            self.play(ReplacementTransform(D22_3, D22_4), ReplacementTransform(uline_D22_3, uline_D22_4))
            self.play(ReplacementTransform(rhomb, pgram))
            self.wait()
            self.play(ReplacementTransform(D22_4, D22_5), ReplacementTransform(uline_D22_4, uline_D22_5))
            self.play(ReplacementTransform(pgram, trpz))
            self.wait()
            self.play(Rotate(Group(def_G[1], D22_5, uline_D22_5, D22_1, uline_D22_1), -PI/1.5, about_point=[-8, 5, 0], axis=UP), FadeOut(trpz))

        def play_def_23():
            self.add(def_G[:-22].shift(7*RIGHT).scale(1/1.5))
            self.play(Draw(D23))
            self.play(Create(uline_D23))
            l1 = FunctionGraph(function=lambda x: 0, x_range=[0, 3]).move_to(canv_center).rotate(0.1*PI).set_color(WHITE_G).set_stroke(color=WHITE_G, width=10).set_z_index(-10)
            l2 = deepcopy(l1).shift(UP)
            self.play(Create(l1), Create(l2))
            self.wait()
            self.play(l1.animate.scale(10), l2.animate.scale(10))
            self.wait()
            self.play(Rotate(Group(def_G[0], D23, uline_D23), -PI/1.5, about_point=[-8, 5, 0], axis=UP), FadeOut(l1, l2))
            
        def play_axs():
            axs = Text("Axioms/Postulates", font="DIOGENES").set_color(BOOK_G).scale(1.2)
            meaning = TexGen(r'$\widehat{=}$ true statements, no proof').next_to(axs, DOWN)
            axmean = VGroup(axs, meaning).move_to(ORIGIN)
            self.play(Draw(axs))
            self.wait()
            self.play(Draw(meaning))
            self.wait()
            self.play(FadeOut(axmean))
            c = Circle(3)
            points_on_circ = [c.point_at_angle(2 * PI * i / 10) for i in range(10)]
            dots_on_circ = VGroup(*[Dot(point, 0.01).set_stroke(BLACK).set_color(BLACK).set_z_index(-1) for point in points_on_circ])
            dot = Dot(dots_on_circ[4].get_center(), 0.2).set_color(BOOK_G).set_stroke(BOOK_G)
            dot.add_updater(lambda mob: mob.move_to(dots_on_circ[4]))
            line = Line(ORIGIN, [1, 1, 0]).set_stroke(BOOK_G, width=6).move_to(dots_on_circ[3])
            line.add_updater(lambda mob: mob.move_to(dots_on_circ[3]))
            surf = SVGMobject('surf.svg').set_color(BOOK_G).set_stroke(BOOK_G).scale(0.5).move_to(dots_on_circ[2])
            surf.add_updater(lambda mob: mob.move_to(dots_on_circ[2].get_center()))
            ang_l1 = Line(ORIGIN, [1, 0, 0]).set_stroke(WHITE, width=4)
            ang_l2 = Line([0.1, -0.1, 0], [0.6, 0.7, 0]).set_stroke(WHITE, width=4)
            ang = VGroup(ang_l1, ang_l2, Angle(ang_l1, ang_l2, radius=0.6).set_stroke(BOOK_G, width=7).set_z_index(-1)).move_to(dots_on_circ[1])
            ang.add_updater(lambda mob: mob.move_to(dots_on_circ[1].get_center()))
            circ = Circle(0.6).set_stroke(BOOK_G, width=6).move_to(dots_on_circ[0])
            circ.add_updater(lambda mob: mob.move_to(dots_on_circ[0]))
            eq = Triangle().scale_to_fit_height(1).set_stroke(BOOK_G, width=6).move_to(dots_on_circ[8])
            eq.add_updater(lambda mob: mob.move_to(dots_on_circ[8]))
            semi = Arc(0.6, start_angle=0, angle=PI, arc_center=canv_center).set_color(WHITE).set_stroke(color=WHITE, width=4).rotate(0.2*PI)
            semi_l = Line(semi.get_start()+[0.02, 0, 0], semi.get_last_point()-[0.02, 0, 0]).set_stroke(BOOK_G, width=7).set_z_index(1)
            sem = VGroup(semi, semi_l).move_to(dots_on_circ[9])
            sem.add_updater(lambda mob: mob.move_to(dots_on_circ[9]))
            cube = Cube(0.8, fill_color=BOOK_G, stroke_width=3).set_stroke(BOOK_G).rotate(-0.2*PI, axis=UP).rotate(0.1*PI, axis=RIGHT).move_to(dots_on_circ[7])
            cube.add_updater(lambda mob: mob.move_to(dots_on_circ[7]))
            trpz = Polygon([3, 0, 0], [5, 0, 0], [6, 2.5, 0], [1, 2.5, 0]).set_color(BOOK_G).set_stroke(color=BOOK_G, width=6).rotate(PI).move_to(dots_on_circ[6]).scale(0.3)
            trpz.add_updater(lambda mob: mob.move_to(dots_on_circ[6]))
            p1 = Line(ORIGIN, [1.2, 0, 0]).set_stroke(BOOK_G, width=6)
            p2 = deepcopy(p1).shift(0.4*DOWN)
            ps = VGroup(p1, p2).rotate(PI/2).move_to(dots_on_circ[5])
            ps.add_updater(lambda mob: mob.move_to(dots_on_circ[5]))
            self.play(LaggedStart(BounceIn(dot), BounceIn(line), GrowFromCenter(surf, rate_func=rate_functions.ease_out_back, run_time=0.5),
                                  GrowFromCenter(ang, rate_func=rate_functions.ease_out_back, run_time=0.5),
                                  GrowFromCenter(circ, rate_func=rate_functions.ease_out_back, run_time=0.5),
                                  GrowFromCenter(sem, rate_func=rate_functions.ease_out_back, run_time=0.5),
                                  GrowFromCenter(eq, rate_func=rate_functions.ease_out_back, run_time=0.5),
                                  GrowFromCenter(cube, rate_func=rate_functions.ease_out_back, run_time=0.5),
                                  GrowFromCenter(trpz, rate_func=rate_functions.ease_out_back, run_time=0.5), 
                                  GrowFromCenter(ps, rate_func=rate_functions.ease_out_back, run_time=0.5), lag_ratio=0.3))
            tree = ImageMobject('tree.png')
            tree.height = 2
            lab = ImageMobject('lab.png').set_z_index(25)
            lab.height = 2
            brain = ImageMobject('brain.png').set_z_index(50)
            brain.height = 2
            cross = TexGen('\ding{55}', col=RED_G, font_sz=300).set_z_index(10)
            cross2 = TexGen('\ding{55}', col=RED_G, font_sz=300).set_z_index(30)
            black_c = Circle(1.5).set_color(BLACK).set_stroke(BLACK).set_fill(BLACK, opacity=1).set_z_index(15)
            black_c2 = Circle(1.5).set_color(BLACK).set_stroke(BLACK).set_fill(BLACK, opacity=1).set_z_index(30)
            self.play(Rotate(dots_on_circ, -0.7*PI, about_point=ORIGIN, run_time=8), 
                      LaggedStart(BounceIn(tree), Draw(cross), FadeIn(black_c), BounceIn(lab), Draw(cross2), FadeIn(black_c2), BounceIn(brain), lag_ratio=1.1))
            Group(tree, cross, lab, cross2, black_c, black_c2).fade(darkness=1)
            self.play(ShrinkToCenter(dots_on_circ.set_z_index(49)))

        def play_ax_1():
            post1 = Text("Postulate 1", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1)
            P1_txt = Text("To draw a straight line from any point to any point.", font_size=25, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1).next_to(post1, DOWN)
            papax1 = SVGMobject("pap.svg", height=1.5).stretch_to_fit_width(P1_txt.width+0.6).to_edge(UP, buff=0.5).set_color(BOOK_G)
            P1 = VGroup(papax1, VGroup(post1, P1_txt).move_to(papax1, aligned_edge=UP).shift(0.3*DOWN), P1_txt)
            dot1 = Dot([-2, -1, 0], 0.2).set_color(BOOK_G).set_stroke(BOOK_G)
            dot2 = Dot([2, 0.5, 0], 0.2).set_color(BOOK_G).set_stroke(BOOK_G)
            line = Line(dot1.get_center(), dot2.get_center()).set_stroke(BOOK_G, width=8).set_z_index(-1)
            line_cp = deepcopy(line)
            mol1 = ImageMobject("mol1.png").move_to(dot1)
            mol2 = ImageMobject("mol2.png")
            mol3 = ImageMobject("mol3.png")
            mol4 = ImageMobject("mol4.png")
            mol5 = ImageMobject("mol5.png")
            mol6 = ImageMobject("mol6.png")
            mol7 = ImageMobject("mol7.png")
            mol1.height = 0.0045
            mol2.height = 0.002
            mol3.height = 0.002
            mol4.height = 0.0022
            mol5.height = 0.003
            mol6.height = 0.002
            mol7.height = 0.004
            mol6.next_to(mol1, 0.0001*UP).shift(0.00035*DOWN)
            mol3.next_to(mol1, 0.003*LEFT+0.0001*UP).shift(0.0005*LEFT+0.00045*DOWN)
            mol4.next_to(mol1, DL, buff=-0.0006)
            mol5.next_to(mol1, 0.0001*DOWN+0.0004*RIGHT).shift(0.0005*RIGHT+0.0018*UP)
            mol2.next_to(mol1, 0.003*LEFT)
            mol7.next_to(mol1, 0.002*RIGHT).shift(0.0015*UP)
            mol1.shift(0.0005*DOWN)
            mols = Group(mol1, mol2, mol3, mol4, mol5, mol6, mol7)
            mols_cp1 = deepcopy(mols).rotate(0.1*PI).scale(5).next_to(mols, RIGHT, buff=0.01)
            mols_cp2 = deepcopy(mols).rotate(0.3*PI).scale(5).next_to(mols, LEFT, buff=0.01)
            mols_cp3 = deepcopy(mols).rotate(-0.1*PI).scale(3).next_to(mols, DOWN, buff=0)
            mols_cp4 = deepcopy(mols).rotate(-0.6*PI).scale(5).next_to(mols, UP, buff=0)
            mols_cp5 = deepcopy(mols).rotate(0.1*PI).scale(5).next_to(mols, 1.5*DR, buff=0)
            mols_cp6 = deepcopy(mols).rotate(0.3*PI).scale(5).next_to(mols, 1.5*UL, buff=0)
            mols_cp7 = deepcopy(mols).rotate(-0.1*PI).scale(3).next_to(mols, 1.5*DL, buff=0)
            mols_cp8 = deepcopy(mols).rotate(-0.6*PI).scale(3).next_to(mols, 1.5*UR, buff=0)
            self.play(GrowFromEdge(P1, edge=UP))
            self.wait()
            self.play(BounceIn(dot1), BounceIn(dot2))
            self.play(Create(line))
            self.wait()
            self.play(Uncreate(line))
            self.play(FadeIn(edge.rotate(np.arctan(1.5/4)).next_to(line, DOWN, buff=0).shift(1.9*UP+2.5*RIGHT), target_position=[3, -4, 0]))
            self.play(Create(line_cp))
            self.play(edge.animate.move_to([3, -4, 0]).fade(darkness=1))
            CAM = self.camera.frame
            CAM.save_state()
            self.wait()
            self.play(LaggedStart(CAM.animate.move_to(dot1.get_center()).scale(0.001), FadeOut(line_cp, run_time=0.2), FadeOut(dot1, run_time=3),
                                  AnimationGroup(GrowFromCenter(mols, run_time=0.6),
                                                 GrowFromPoint(mols_cp1, dot1.get_center()+[0.00005, 0, 0], run_time=0.3), 
                                                 GrowFromPoint(mols_cp2, dot1.get_center()-[0.00005, 0, 0], run_time=0.3), 
                                                 GrowFromPoint(mols_cp3, dot1.get_center()-[0, 0.00005, 0], run_time=0.3), 
                                                 GrowFromPoint(mols_cp4, dot1.get_center()+[0, 0.00005, 0], run_time=0.3),
                                                 GrowFromPoint(mols_cp5, dot1.get_center()+[0.00005, -0.00005, 0], run_time=0.1), 
                                                 GrowFromPoint(mols_cp6, dot1.get_center()+[-0.00005, 0.00005, 0], run_time=0.1), 
                                                 GrowFromPoint(mols_cp7, dot1.get_center()+[-0.00005, -0.00005, 0], run_time=0.1), 
                                                 GrowFromPoint(mols_cp8, dot1.get_center()+[0.00005, 0.00005, 0], run_time=0.1)), lag_ratio=0.7))
            self.play(LaggedStart(AnimationGroup(ShrinkToCenter(mols),
                                                 mols_cp1.animate.scale(0).move_to(dot1.get_center()+[0.00005, 0, 0]), 
                                                 mols_cp2.animate.scale(0).move_to(dot1.get_center()-[0.00005, 0, 0]), 
                                                 mols_cp3.animate.scale(0).move_to(dot1.get_center()-[0, 0.00005, 0]), 
                                                 mols_cp4.animate.scale(0).move_to(dot1.get_center()+[0, 0.00005, 0]),
                                                 mols_cp5.animate.scale(0).move_to(dot1.get_center()+[0.00005, -0.00005, 0]), 
                                                 mols_cp6.animate.scale(0).move_to(dot1.get_center()+[-0.00005, 0.00005, 0]), 
                                                 mols_cp7.animate.scale(0).move_to(dot1.get_center()+[-0.00005, -0.00005, 0]), 
                                                 mols_cp8.animate.scale(0).move_to(dot1.get_center()+[0.00005, 0.00005, 0]), run_time=0.6), FadeIn(dot1, run_time=2), AnimationGroup(FadeIn(line_cp, run_time=0.01), Restore(CAM, rate_func=rate_functions.rush_from)), lag_ratio=0.8), run_time=4)
            post2 = Text("Postulate 2", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1)
            P2_txt = Text("To produce a finite straight line continuously in a straight line.", font_size=25, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1).next_to(post2, DOWN)
            papax2 = SVGMobject("pap.svg", height=1.5).stretch_to_fit_width(P2_txt.width+0.6).to_edge(UP, buff=0.5).set_color(BOOK_G)
            P2 = VGroup(papax2, VGroup(post2, P2_txt).move_to(papax2, aligned_edge=UP).shift(0.3*DOWN), P2_txt)
            self.wait()
            self.play(LaggedStart(P1.animate.scale(0).move_to(P1, aligned_edge=UP), GrowFromEdge(P2, edge=UP), lag_ratio=1.1), FadeOut(dot1, dot2, line_cp))

        def play_ax_2_4():
            post2 = Text("Postulate 2", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1)
            P2_txt = Text("To produce a finite straight line continuously in a straight line.", font_size=25, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1).next_to(post2, DOWN)
            papax2 = SVGMobject("pap.svg", height=1.5).stretch_to_fit_width(P2_txt.width+0.6).to_edge(UP, buff=0.5).set_color(BOOK_G)
            P2 = VGroup(papax2, VGroup(post2, P2_txt).move_to(papax2, aligned_edge=UP).shift(0.3*DOWN), P2_txt)
            self.add(P2)
            line = Line([-2, 0.5, 0], [2, -1, 0]).set_stroke(BOOK_G, 8)
            self.play(BounceIn(line))
            self.wait()
            self.play(line.animate.scale(10))
            self.wait()
            post3 = Text("Postulate 3", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1)
            P3_txt = Text("To describe a circle with any center and radius.", font_size=25, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1).next_to(post3, DOWN)
            papax3 = SVGMobject("pap.svg", height=1.5).stretch_to_fit_width(P3_txt.width+0.6).to_edge(UP, buff=0.5).set_color(BOOK_G)
            P3 = VGroup(papax3, VGroup(post3, P3_txt).move_to(papax3, aligned_edge=UP).shift(0.3*DOWN), P3_txt)
            self.play(LaggedStart(P2.animate.scale(0).move_to(P2, aligned_edge=UP), GrowFromEdge(P3, edge=UP), lag_ratio=1.1), FadeOut(line))
            self.wait()
            comp = SVGMobject('comp.svg').set_color(YELL_G).set_stroke(YELL_G)
            comp.height = 4
            comp.shift(DOWN)
            circ = CompCirc([0, -1, 0], [2, -1, 0], end_col=YELL_G).set_z_index(1)
            self.play(LaggedStart(circ.animate.scale_to_fit_width(0.7).move_to(ORIGIN).shift(0.2*UP).fade(darkness=1), Draw(comp), lag_ratio=0.5))
            self.wait()
            self.play(LaggedStart(P3.animate.scale(0).move_to(P3, aligned_edge=UP), BounceIn(edge.next_to(comp, UP).shift(UP)), lag_ratio=0.9))
            self.wait()
            post4 = Text("Postulate 4", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1)
            P4_txt = Text("That all right angles equal one another.", font_size=25, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1).next_to(post4, DOWN)
            papax4 = SVGMobject("pap.svg", height=1.5).stretch_to_fit_width(P4_txt.width+0.6).to_edge(UP, buff=0.5).set_color(BOOK_G)
            P4 = VGroup(papax4, VGroup(post4, P4_txt).move_to(papax4, aligned_edge=UP).shift(0.3*DOWN), P4_txt)
            self.play(LaggedStart(FadeOut(comp, edge), GrowFromEdge(P4, edge=UP), lag_ratio=1))
            self.wait()
            l1 = Line(ORIGIN, [2, 0, 0]).set_stroke(WHITE_G, 8)
            l2 = Line([1, -1, 0], [1, 1, 0]).set_stroke(WHITE_G, 8)
            a1_lines = VGroup(l1, l2).move_to([0, -1, 0]).scale(2)
            a1 = Angle(l1, l2, radius=1).set_stroke(BOOK_G, 10).set_z_index(-1)
            a2_lines = deepcopy(a1_lines).stretch_to_fit_width(2.5).stretch_to_fit_height(3.5).rotate(PI/2-0.1*PI).next_to(a1_lines, 3*LEFT)
            a2 = Angle(a2_lines[0], a2_lines[1], radius=1).set_stroke(BOOK_G, 10).set_z_index(-1)
            a3_lines = deepcopy(a1_lines).stretch_to_fit_width(5).stretch_to_fit_height(2.3).rotate(-0.3*PI).next_to(a1_lines, 3*RIGHT)
            a3 = Angle(a3_lines[0], a3_lines[1], radius=1).set_stroke(BOOK_G, 10).set_z_index(-1)
            self.play(LaggedStart(BounceIn(a2_lines), Create(a2), BounceIn(a1_lines), Create(a1), BounceIn(a3_lines), Create(a3), lag_ratio=0.2))
            self.wait()
            post5 = Text("Postulate 5", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1)
            P5_txt = Text("That, if a straight line falling on two straight lines makes the interior angles on the same side\nless than two right angles, the two straight lines, if produced indefinitely, meet on that side\non which are the angles less than the two right angles.", font_size=25, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1).next_to(post5, DOWN)
            papax5 = SVGMobject("pap.svg", height=2.6).stretch_to_fit_width(P5_txt.width+0.8).to_edge(UP, buff=0.5).set_color(BOOK_G)
            P5 = VGroup(papax5, VGroup(post5, P5_txt).move_to(papax5, aligned_edge=UP).shift(0.3*DOWN), P5_txt)
            self.play(LaggedStart(P4.animate.scale(0).move_to(P4, aligned_edge=UP), GrowFromEdge(P5, edge=UP), lag_ratio=1.1), FadeOut(a1, a2, a3, run_time=0.7), VGroup(a1_lines, a2_lines, a3_lines).animate.fade(darkness=1))

        def play_ax_5():
            post5 = Text("Postulate 5", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1)
            P5_txt = Text("That, if a straight line falling on two straight lines makes the interior angles on the same side\nless than two right angles, the two straight lines, if produced indefinitely, meet on that side\non which are the angles less than the two right angles.", font_size=25, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1).next_to(post5, DOWN)
            papax5 = SVGMobject("pap.svg", height=2.6).stretch_to_fit_width(P5_txt.width+0.8).to_edge(UP, buff=0.5).set_color(BOOK_G)
            P5 = VGroup(papax5, VGroup(post5, P5_txt).move_to(papax5, aligned_edge=UP).shift(0.3*DOWN), P5_txt)
            self.add(P5)
            self.wait()
            l_bot = Line([-2, -2.5, 0], [2, -2.5, 0]).set_stroke(WHITE_G, 8)
            l_top = deepcopy(l_bot).scale(1.5).shift(2*UP).rotate(-0.03*PI)
            l_n = Line([0, 0.5, 0], [0, -3.5, 0]).set_stroke(WHITE_G, 8)
            self.play(Create(l_bot), Create(l_top))
            self.wait()
            self.play(Create(l_n))
            self.wait()
            a_top = Angle(l_n, l_top, radius=0.6).set_stroke(BOOK_G, 8).set_z_index(-1)
            a_bot = Angle(deepcopy(l_n).put_start_and_end_on(l_n.get_last_point(), l_n.get_start()), l_bot, other_angle=True, radius=0.6).set_stroke(BOOK_G, 8).set_z_index(-1)
            a_bot_cp = deepcopy(a_bot)
            a_bot.add_updater(lambda mob: mob.become(Angle(deepcopy(l_n).put_start_and_end_on(l_n.get_last_point(), l_n.get_start()), l_bot, other_angle=True, radius=0.6).set_stroke(BOOK_G, 8).set_z_index(-1)))
            self.play(Create(a_top), Create(a_bot))
            self.wait()
            less = TexGen(r'< 180°', col=BOOK_G, font_sz=80).move_to([2, -1.6, 0])
            eq = TexGen(r'= 180°', col=BOOK_G, font_sz=80).move_to(less)
            self.play(ReplacementTransform(VGroup(deepcopy(a_top), a_bot_cp), less))
            self.play(l_top.animate.scale(20), l_bot.animate.scale(20))
            CAM = self.camera.frame
            CAM.save_state()
            self.add(Dot([21, -2.5, 0], radius=0.2).set_stroke(BOOK_G).set_color(BOOK_G))
            self.play(CAM.animate.shift(20*RIGHT), run_time=2)
            self.wait()
            self.play(Restore(CAM), run_time=2)
            self.wait()
            self.play(l_bot.animate.rotate(-0.03*PI), ReplacementTransform(less, eq))
            a_bot.clear_updaters()
            self.play(l_n.animate.fade(darkness=1), a_top.animate.fade(darkness=1), a_bot.animate.fade(darkness=1), FadeOut(eq),
                      l_top.animate.set_stroke(BOOK_G), l_bot.animate.set_stroke(BOOK_G))
            self.wait()
            self.play(P5.animate.shift(10*UP), VGroup(l_top, l_bot).animate.shift(10*DOWN))

        def play_tube():
            def tube(u, v):
                radius = 2+0.3*np.sin(2*v)
                x = radius*np.cos(u)
                y = radius*np.sin(u)
                z = v
                return np.array([x, y, z])
            tube_surf = Surface(tube, u_range=[0, TAU], v_range=[-3, 2], resolution=(64, 96), fill_opacity=0.8).set_color(BOOK_G).rotate(PI/3, axis=RIGHT).move_to(ORIGIN)
            sph = Sphere(center=ORIGIN, radius=2.5, resolution=(64, 96), fill_opacity=0.8).set_color(BOOK_G).rotate(PI/3, axis=RIGHT).move_to(ORIGIN)
            self.begin_ambient_camera_rotation(rate=0.4, about="phi")
            self.play(Create(sph))
            self.wait(1.1)
            self.play(ReplacementTransform(sph, tube_surf))
            self.wait(4)
            self.stop_ambient_camera_rotation()

        def play_commns():
            papy = SVGMobject("pap.svg").rotate(PI/2).set_color(BOOK_G)
            papy.height = 5
            papy.move_to(ORIGIN)
            cns = Text("Common Notions", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1).move_to(papy, aligned_edge=UP).shift(0.3*DOWN)
            cn1 = Text("1. Things which equal the same thing also equal one another.", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1).next_to(cns, 2*DOWN).shift(0.3*LEFT)
            cn2 = Text("2. If equals are added to equals, then the wholes are equal.", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1).next_to(cn1, DOWN, aligned_edge=LEFT)
            cn3 = Text("3. If equals are subtracted from equals, then the remainders are equal.", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1).next_to(cn2, DOWN, aligned_edge=LEFT)
            cn4 = Text("4. Things which coincide with one another equal one another.", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1).next_to(cn3, DOWN, aligned_edge=LEFT)
            cn5 = Text("5. The whole is greater than the part.", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).set_z_index(1).next_to(cn4, DOWN, aligned_edge=LEFT)
            papy.stretch_to_fit_width(cn3.width+0.9)
            cnp = VGroup(papy, cns, VGroup(cn1, cn2, cn3, cn4, cn5).set_x(0))
            self.play(GrowFromCenter(cnp))
            self.wait()
            self.play(ShrinkToCenter(cnp))

        def play_props():
            prop = Text("Theorems/Propositions", font="DIOGENES").set_color(BOOK_G).scale(1.2)
            meaning = TexGen(r'$\widehat{=}$ true statements, with proof').next_to(prop, DOWN)
            prop_mean = VGroup(prop, meaning).move_to(ORIGIN)
            self.play(Draw(prop))
            self.wait()
            self.play(Draw(meaning))
            self.wait()
            defs = Text("D1 - D23", font="DIOGENES").set_color(BOOK_G)
            axs = Text("P1 - P5", font="DIOGENES").set_color(BOOK_G)
            cns = Text("C1 - C5", font="DIOGENES").set_color(BOOK_G).next_to(axs, DOWN)
            VGroup(defs, VGroup(axs, cns).next_to(defs, 3*RIGHT)).next_to(meaning, 3*DOWN)
            self.play(Draw(defs))
            self.wait()
            self.play(Draw(axs), Draw(cns))
            self.wait()
            comp = SVGMobject('comp.svg').set_color(YELL_G).set_stroke(YELL_G).scale_to_fit_height(1.7)
            edge.rotate(PI/2).scale_to_fit_height(1.7)
            tools = VGroup(edge, comp.next_to(edge, 3*RIGHT)).next_to(meaning, 3*DOWN)
            self.play(FadeOut(defs, axs, cns))
            self.play(Draw(edge), Draw(comp))
            self.wait()
            self.play(FadeOut(edge, comp, meaning))
            prop1 = Text("Proposition 1: To construct an equilateral triangle on a given finite straight line.", font="DIOGENES", font_size=30).set_color(BOOK_G).to_edge(UP, buff=0.5)
            self.play(ReplacementTransform(prop, prop1))

        def play_prop_1():
            prop1 = Text("Proposition 1: To construct an equilateral triangle on a given finite straight line.", font="DIOGENES", font_size=30).set_color(BOOK_G).to_edge(UP, buff=0.5)
            proof = TexGen(r"\textit{Proof}.", font_sz=40).next_to(prop1, DOWN, aligned_edge=LEFT)
            self.add(prop1)
            line = Line([-1, 0, 0], [1.2, 0, 0]).set_stroke(width=6)
            eq_trig = Triangle().scale_to_fit_width(line.width).move_to(line, aligned_edge=DOWN).set_stroke(BOOK_G, width=6)
            d3 = Dot(eq_trig.get_corner(UP), 0.1).set_color(BOOK_G).set_stroke(BOOK_G)
            d4 = deepcopy(d3).shift(eq_trig.height*2*DOWN)
            VGroup(eq_trig, line, d3, d4).rotate(0.1*PI).move_to(ORIGIN).shift(1.2*DOWN)
            self.play(Create(line))
            self.wait()
            self.play(Draw(proof))
            self.wait()
            D3 = Text("D3", font="DIOGENES", font_size=30).set_color(BOOK_G).next_to(proof, DOWN, aligned_edge=LEFT)
            arr1 = TexGen(r'\Rightarrow', isMath=True, font_sz=40).next_to(D3, RIGHT)
            P3 = Text("P3", font="DIOGENES", font_size=30).set_color(BOOK_G).next_to(arr1, RIGHT)
            arr2 = TexGen(r'\Rightarrow', isMath=True, font_sz=40).next_to(P3, RIGHT)
            P1 = Text("P1", font="DIOGENES", font_size=30).set_color(BOOK_G).next_to(arr2, RIGHT)
            arr3 = TexGen(r'\Rightarrow', isMath=True, font_sz=40).next_to(P1, RIGHT)
            D19 = Text("D19", font="DIOGENES", font_size=30).set_color(BOOK_G).next_to(arr3, RIGHT)
            arr4 = TexGen(r'\Rightarrow', isMath=True, font_sz=40).next_to(D19, RIGHT)
            DC = Text("D15, C1", font="DIOGENES", font_size=30).set_color(BOOK_G).next_to(arr4, RIGHT).align_to(D19, UP)
            arr5 = TexGen(r'\Rightarrow', isMath=True, font_sz=40).next_to(DC, RIGHT).set_y(arr4.get_y())
            D20 = Text("D20", font="DIOGENES", font_size=30).set_color(BOOK_G).next_to(arr5, RIGHT)
            self.play(Draw(D3))
            d1 = Dot(line.get_start(), 0.1).set_color(BOOK_G).set_stroke(BOOK_G)
            d2 = Dot(line.get_last_point(), 0.1).set_color(BOOK_G).set_stroke(BOOK_G)
            self.play(Create(d1), Create(d2))
            self.play(d1.animate.set_color(WHITE_G).set_stroke(WHITE_G), d2.animate.set_color(WHITE_G).set_stroke(WHITE_G))
            self.wait()
            self.play(Draw(arr1), Draw(P3))
            c1 = CompCirc(d1.get_center(), d2.get_center())
            c2 = CompCirc(d2.get_center(), d1.get_center())
            self.play(Create(d3), Create(d4))
            self.play(d3.animate.set_color(WHITE_G).set_stroke(WHITE_G), d4.animate.set_color(WHITE_G).set_stroke(WHITE_G))
            self.wait()
            self.play(Draw(arr2), Draw(P1))
            l1 = Line(d1.get_center(), d3.get_center()).set_stroke(BOOK_G, width=6).set_z_index(-1)
            l2 = Line(d3.get_center(), d2.get_center()).set_stroke(BOOK_G, width=6).set_z_index(-1)
            edge.scale(0.8).move_to(d1.get_center(), aligned_edge=UP).shift(RIGHT).rotate(PI/3+0.1*PI, about_point=d1.get_center())
            self.play(FadeIn(edge, target_position=[2, -5, 0]))
            self.play(Create(l1))
            self.play(edge.animate.rotate(PI/3, about_point=d3.get_center()))
            self.play(Create(l2))
            self.play(edge.animate.move_to([2, -5, 0]).fade(darkness=1))
            self.play(l1.animate.set_stroke(WHITE_G), l2.animate.set_stroke(WHITE_G))
            self.wait()
            self.play(Draw(arr3), Draw(D19))
            d1.set_z_index(1)
            d2.set_z_index(1)
            d3.set_z_index(1)
            self.play(FadeIn(eq_trig.set_z_index(0.5)))
            self.wait()
            self.play(Draw(arr4), Draw(DC))
            self.wait()
            self.play(Draw(arr5), Draw(D20))
            self.remove(l1, l2, line)
            self.play(FadeOut(d1, d2, d3, d4, c1, c2))
            qed = TexGen(r"\textit{q.e.d.}", font_sz=40).next_to(D20, DR, buff=0.1)
            self.wait()
            self.play(Draw(qed))
            
        def play_end():
            props_total = Text("465 Propositions", font="DIOGENES", font_size=65).set_color(BOOK_G).to_edge(UP, buff=1)
            pyth = TexGen(r'Pythagorean theorem', font_sz=60).next_to(props_total, 1.5*DOWN)
            a_sum = TexGen(r'Sum of Interior Angles', font_sz=60).next_to(pyth, DOWN)
            thales = TexGen(r"Thales' theorem", font_sz=60).next_to(a_sum, DOWN)
            euc = TexGen(r"Euclidean algorithm", font_sz=60).next_to(thales, 1.5*DOWN)
            inf = TexGen(r"Infinitude of primes", font_sz=60).next_to(euc, DOWN)
            dots = TexGen(r"\vdots", isMath=True, font_sz=60).next_to(inf, DOWN)
            self.play(Draw(props_total))
            self.wait()
            self.play(GrowFromPoint(pyth, props_total.get_center()-[0, 0.2, 0]))
            self.wait()
            self.play(GrowFromPoint(a_sum, props_total.get_center()-[0, 0.2, 0]))
            self.wait()
            self.play(GrowFromPoint(thales, props_total.get_center()-[0, 0.2, 0]))
            self.wait()
            self.play(GrowFromPoint(euc, props_total.get_center()-[0, 0.2, 0]))
            self.wait()
            self.play(GrowFromPoint(inf, props_total.get_center()-[0, 0.2, 0]))
            self.play(Draw(dots))
            self.wait()
            self.play(LaggedStart(props_total.animate.move_to([0, 10, 0]),
                                  pyth.animate.move_to([0, 10, 0]),
                                  a_sum.animate.move_to([0, 10, 0]),
                                  thales.animate.move_to([0, 10, 0]),
                                  euc.animate.move_to([0, 10, 0]),
                                  inf.animate.move_to([0, 10, 0]),
                                  dots.animate.move_to([0, 10, 0]), lag_ratio=0.15), run_time=1.1)
            self.wait()
            arr = TexGen(r'\Rightarrow', isMath=True, font_sz=130)
            one_txt = TexGen(r'one', font_sz=130)
            black_l1 = TexGen(r'l', col=BLACK_G, font_sz=130).next_to(one_txt, LEFT, buff=0).align_to(one_txt, DOWN)
            black_l2 = TexGen(r'l', col=BLACK_G, font_sz=130).next_to(one_txt, RIGHT, buff=0).align_to(one_txt, DOWN)
            one = VGroup(black_l1, one_txt, black_l2).next_to(arr, LEFT, buff=1)
            all_txt = TexGen(r'all', font_sz=130)
            black_l3 = TexGen(r'l', col=BLACK_G, font_sz=130).next_to(all_txt, LEFT, buff=0).align_to(all_txt, DOWN)
            black_l4 = TexGen(r'l', col=BLACK_G, font_sz=130).next_to(all_txt, RIGHT, buff=0).align_to(all_txt, DOWN)
            alll = VGroup(black_l3, all_txt, black_l4).next_to(arr, RIGHT, buff=1)
            self.play(Draw(one))
            self.wait()
            self.play(Draw(arr))
            self.play(Draw(alll))
            self.wait()
            self.play(Swap(one, alll))


        # GLOBALS  
        papyrus = SVGMobject("pap.svg", height=6.3).stretch_to_fit_width(4.7).to_edge(LEFT, buff=0.5).set_color(BOOK_G)
        uline = SVGMobject("uline.svg")

        D10 = Text("When a straight line standing\non a straight line makes the\nadjacent angles equal to one\nanother, each of the equal\nangles is right, and the straight\nline standing on the other is\ncalled a perpendicular to that\non which it stands.", font_size=25, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(papyrus, aligned_edge=UL).shift(1.5*DOWN+0.3*RIGHT).set_z_index(13.1)
        def10 = Text("Definition 10", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).next_to(D10, 2*UP).set_x(papyrus.get_x())
        uline1_D10 = deepcopy(uline).scale_to_fit_width(D10[102:107].width).next_to(D10[102:107], DOWN, buff=-0.09).set_z_index(13.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        uline2_D10 = deepcopy(uline).scale_to_fit_width(D10[153:166].width).next_to(D10[153:166], DOWN, buff=0.01).set_z_index(13.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def1 = Text("Definition 1", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D1 = Text("A point is that which has no\npart.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(22.1).set_color(INK_G)
        uline_D1 = deepcopy(uline).scale_to_fit_width(D1[1:6].width).next_to(D1[1:6], DOWN, buff=0.01).set_z_index(22.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def2 = Text("Definition 2", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D2 = Text("A line is breadthless length.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(21.1).set_color(INK_G)
        uline_D2 = deepcopy(uline).scale_to_fit_width(D2[1:5].width).next_to(D2[1:5], DOWN, buff=0.05).set_z_index(21.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def3 = Text("Definition 3", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D3 = Text("The ends of a line are points.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(20.1).set_color(INK_G)
        
        def4 = Text("Definition 4", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D4 = Text("A straight line is a line which\nlies evenly with the points on\nitself.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(19.1).set_color(INK_G)
        uline_D4 = deepcopy(uline).scale_to_fit_width(D4[1:13].width).next_to(D4[1:13], DOWN, buff=-0.12).set_z_index(19.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def5 = Text("Definition 5", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D5 = Text("A surface is that which has\nlength and breadth only.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(18.1).set_color(INK_G)
        uline_D5 = deepcopy(uline).scale_to_fit_width(D5[1:8].width).next_to(D5[1:8], DOWN, buff=0.05).set_z_index(18.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def6 = Text("Definition 6", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D6 = Text("The edges of a surface are\nlines.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(17.1).set_color(INK_G)
        
        def7 = Text("Definition 7", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D7 = Text("A plane surface is a surface\nwhich lies evenly with the\nstraight lines on itself.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(16.1).set_color(INK_G)
        uline_D7 = deepcopy(uline).scale_to_fit_width(D7[1:13].width).next_to(D7[1:13], DOWN, buff=-0.01).set_z_index(16.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def8 = Text("Definition 8", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D8 = Text("A plane angle is the inclination\nto one another of two lines in\na plane which meet one\nanother and do not lie in a\nstraight line.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(15.1).set_color(INK_G)
        uline_D8 = deepcopy(uline).scale_to_fit_width(D8[1:11].width).next_to(D8[1:11], DOWN, buff=-0.1).set_z_index(15.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def9 = Text("Definition 9", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D9 = Text("And when the lines containing\nthe angle are straight, the\nangle is called rectilinear.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(14.1).set_color(INK_G)
        uline_D9 = deepcopy(uline).scale_to_fit_width(D9[61:73].width).next_to(D9[61:73], DOWN, buff=0.05).set_z_index(14.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def11 = Text("Definition 11", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D11 = Text("An obtuse angle is an angle\ngreater than a right angle.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(12.1).set_color(INK_G)
        uline_D11 = deepcopy(uline).scale_to_fit_width(D11[2:13].width).next_to(D11[2:13], DOWN, buff=-0.12).set_z_index(12.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def12 = Text("Definition 12", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D12 = Text("An acute angle is an angle\nless than a right angle.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(11.1).set_color(INK_G)
        uline_D12 = deepcopy(uline).scale_to_fit_width(D12[2:12].width).next_to(D12[2:12], DOWN, buff=-0.12).set_z_index(11.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def13 = Text("Definition 13", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D13 = Text("A boundary is that which is an\nextremity of anything.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(10.1).set_color(INK_G)
        uline_D13 = deepcopy(uline).scale_to_fit_width(D13[1:9].width).next_to(D13[1:9], DOWN, buff=-0.06).set_z_index(10.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def14 = Text("Definition 14", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D14 = Text("A figure is that which is\ncontained by any boundary\nor boundaries.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(9.1).set_color(INK_G)
        uline_D14 = deepcopy(uline).scale_to_fit_width(D14[1:7].width).next_to(D14[1:7], DOWN, buff=-0.1).set_z_index(9.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def15 = Text("Definition 15", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D15 = Text("A circle is a plane figure\ncontained by one line such\nthat all the straight lines\nfalling upon it from one point\namong those lying within the\nfigure equal one another.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(8.1).set_color(INK_G)
        uline_D15 = deepcopy(uline).scale_to_fit_width(D15[1:7].width).next_to(D15[1:7], DOWN, buff=0.05).set_z_index(8.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def16 = Text("Definition 16", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D16 = Text("And the point is called the\ncenter of the circle.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(7.1).set_color(INK_G)
        uline_D16 = deepcopy(uline).scale_to_fit_width(D16[22:28].width).next_to(D16[22:28], DOWN, buff=0.05).set_z_index(7.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def17 = Text("Definition 17", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D17 = Text("A diameter of the circle is any\nstraight line drawn through\nthe center and terminated in\nboth directions by the\ncircumference of the circle,\nand such a straight line also\nbisects the circle.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(6.1).set_color(INK_G)
        uline_D17 = deepcopy(uline).scale_to_fit_width(D17[1:9].width).next_to(D17[1:9], DOWN, buff=0.05).set_z_index(6.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def18 = Text("Definition 18", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D18 = Text("A semicircle is the figure\ncontained by the diameter\nand the circumference cut off\nby it. And the center of the\nsemicircle is the same as that\nof the circle.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(5.1).set_color(INK_G)
        uline_D18 = deepcopy(uline).scale_to_fit_width(D18[1:11].width).next_to(D18[1:11], DOWN, buff=0.05).set_z_index(5.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def19 = Text("Definition 19", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D19_1 = Text("Rectilinear figures are those\nwhich are contained by\nstraight lines; . . .", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(4.1).set_color(INK_G)
        D19_2 = Text(". . . trilateral figures being those\ncontained by three; . . .", font_size=25, font="DIOGENES", line_spacing=1).next_to(D19_1, DOWN, aligned_edge=LEFT).set_z_index(4.1).set_color(INK_G)
        D19_3 = Text(". . . quadrilateral those\ncontained by four; . . .", font_size=25, font="DIOGENES", line_spacing=1).next_to(D19_1, DOWN, aligned_edge=LEFT).set_z_index(4.1).set_color(INK_G)
        D19_4 = Text(". . . and multilateral those\ncontained by more than four\nstraight lines.", font_size=25, font="DIOGENES", line_spacing=1).next_to(D19_1, DOWN, aligned_edge=LEFT).set_z_index(4.1).set_color(INK_G)
        uline_D19_1 = deepcopy(uline).scale_to_fit_width(D19_1[0:10].width).next_to(D19_1[1:10], DOWN, buff=0.05).set_z_index(4.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        uline_D19_2 = deepcopy(uline).scale_to_fit_width(D19_2[3:12].width).next_to(D19_2[3:12], DOWN, buff=0.05).set_z_index(4.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        uline_D19_3 = deepcopy(uline).scale_to_fit_width(D19_3[3:15].width).next_to(D19_3[3:15], DOWN, buff=-0.02).set_z_index(4.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        uline_D19_4 = deepcopy(uline).scale_to_fit_width(D19_4[6:18].width).next_to(D19_4[6:18], DOWN, buff=0.05).set_z_index(4.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def20 = Text("Definition 20", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D20_1 = Text("Of trilateral figures, an\nequilateral triangle is that which\nhas its three sides equal; . . .", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(3.1).set_color(INK_G)
        D20_2 = Text(". . . an isosceles triangle that\nwhich has two of its sides alone\nequal; . . .", font_size=25, font="DIOGENES", line_spacing=1).next_to(D20_1, DOWN, aligned_edge=LEFT).set_z_index(3.1).set_color(INK_G)
        D20_3 = Text(". . . and a scalene triangle that\nwhich has its three sides unequal.", font_size=25, font="DIOGENES", line_spacing=1).next_to(D20_1, DOWN, aligned_edge=LEFT).set_z_index(3.1).set_color(INK_G)
        uline_D20_1 = deepcopy(uline).scale_to_fit_width(D20_1[22:32].width).next_to(D20_1[22:32], DOWN, buff=-0.03).set_z_index(3.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        uline_D20_2 = deepcopy(uline).scale_to_fit_width(D20_2[5:14].width).next_to(D20_2[5:14], DOWN, buff=0.05).set_z_index(3.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        uline_D20_3 = deepcopy(uline).scale_to_fit_width(D20_3[7:14].width).next_to(D20_3[7:14], DOWN, buff=0.05).set_z_index(3.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
         
        def21 = Text("Definition 21", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D21_1 = Text("Further, of trilateral figures, a\nright-angled triangle is that\nwhich has a right angle; . . .", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(2.1).set_color(INK_G)
        D21_2 = Text(". . . an obtuse-angled triangle\nthat which has an obtuse\nangle; . . .", font_size=25, font="DIOGENES", line_spacing=1).next_to(D21_1, DOWN, aligned_edge=LEFT).set_z_index(2.1).set_color(INK_G)
        D21_3 = Text(". . . and an acute-angled\ntriangle that which has its\nthree angles acute.", font_size=25, font="DIOGENES", line_spacing=1).next_to(D21_1, DOWN, aligned_edge=LEFT).set_z_index(2.1).set_color(INK_G)
        uline_D21_1 = deepcopy(uline).scale_to_fit_width(D21_1[29:41].width).next_to(D21_1[29:41], DOWN, buff=-0.1).set_z_index(2.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        uline_D21_2 = deepcopy(uline).scale_to_fit_width(D21_2[5:18].width).next_to(D21_2[5:18], DOWN, buff=-0.12).set_z_index(2.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        uline_D21_3 = deepcopy(uline).scale_to_fit_width(D21_3[8:20].width).next_to(D21_3[8:20], DOWN, buff=-0.12).set_z_index(2.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        def22 = Text("Definition 22", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D22_1 = Text("Of quadrilateral figures, a square\nis that which is both equilateral\nand right-angled; . . .", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(1.1).set_color(INK_G)
        D22_2 = Text(". . . an oblong that which is\nright-angled but not\nequilateral; . . .", font_size=25, font="DIOGENES", line_spacing=1).next_to(D22_1, DOWN, aligned_edge=LEFT).set_z_index(1.1).set_color(INK_G)
        D22_3 = Text(". . . a rhombus that which is\nequilateral but not right-angled;\n. . .", font_size=25, font="DIOGENES", line_spacing=1).next_to(D22_1, DOWN, aligned_edge=LEFT).set_z_index(1.1).set_color(INK_G)
        D22_4 = Text(". . . and a rhomboid that which\nhas its opposite sides and angles\nequal to one another but is\nneither equilateral nor\nright-angled;. . .", font_size=25, font="DIOGENES", line_spacing=1).next_to(D22_1, DOWN, aligned_edge=LEFT).set_z_index(1.1).set_color(INK_G)
        D22_5 = Text(". . . and let quadrilaterals other\nthan these be called trapezia.", font_size=25, font="DIOGENES", line_spacing=1).next_to(D22_1, DOWN, aligned_edge=LEFT).set_z_index(1.1).set_color(INK_G)  
        uline_D22_1 = deepcopy(uline).scale_to_fit_width(D22_1[24:30].width).next_to(D22_1[24:30], DOWN, buff=-0.05).set_z_index(1.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        uline_D22_2 = deepcopy(uline).scale_to_fit_width(D22_2[5:11].width).next_to(D22_2[5:11], DOWN, buff=-0.12).set_z_index(1.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        uline_D22_3 = deepcopy(uline).scale_to_fit_width(D22_3[4:11].width).next_to(D22_3[4:11], DOWN, buff=0.05).set_z_index(1.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        uline_D22_4 = deepcopy(uline).scale_to_fit_width(D22_4[7:15].width).next_to(D22_4[7:15], DOWN, buff=0.05).set_z_index(1.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        uline_D22_5 = deepcopy(uline).scale_to_fit_width(D22_5[45:53].width).next_to(D22_5[45:53], DOWN, buff=-0.05).set_z_index(1.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
    
        def23 = Text("Definition 23", font_size=30, font="DIOGENES", line_spacing=1).set_color(INK_G).move_to(def10).set_x(papyrus.get_x())
        D23 = Text("Parallel straight lines are straight\nlines which, being in the same\nplane and being produced\nindefinitely in both directions,\ndo not meet one another in\neither direction.", font_size=25, font="DIOGENES", line_spacing=1).move_to(D10, aligned_edge=UL).set_z_index(0.1).set_color(INK_G)
        uline_D23 = deepcopy(uline).scale_to_fit_width(D23[0:8].width).next_to(D23[0:8], DOWN, buff=0.05).set_z_index(0.1).set_color(INK_G).set_fill(color=INK_G, opacity=1).set_stroke(color=INK_G, width=4)
        
        defs = [def1, def2, def3, def4, def5, def6, def7, def8, def9, def10, def11, def12, def13, def14, def15, def16, def17, def18, def19, def20, def21, def22, def23]
        papys = []
        def_anims = []
        def_G = VGroup()
        for i in range(23):
            papys.append(deepcopy(papyrus))
            def_G.add(VGroup(papys[i].set_z_index(i), defs[22-i].set_z_index(i+0.1)).shift(7*LEFT).scale(1.5))
            def_anims.append(def_G[i].animate.shift(7*RIGHT).scale(1/1.5))
        canv_center = np.array([2.5, 0, 0])
        
        books = VGroup()
        for i in range(13):
            books.add(VGroup(SVGMobject(r'bk4.svg', width=0.7).set_color(BOOK_G), Text(f'{i+1}', font="DIOGENES", font_size=33).set_color(INK_G).shift(0.05*UP)).shift(i*0.85*RIGHT))
        elements_title = Text('ELEMENTS', font="DIOGENES", font_size=35).set_color(INK_G).shift(UP)
        elements_by = Text('by', font="DIOGENES", font_size=35).set_color(INK_G).next_to(elements_title, 2.5*DOWN)
        elements = VGroup(SVGMobject(r'bk4.svg', width=2.8, fill_color=WHITE).set_color(BOOK_G), elements_title, elements_by, Text('Euclid', font="DIOGENES", font_size=35).set_color(INK_G).next_to(elements_by, DOWN))
        hilberts_book = VGroup(SVGMobject(r'hbook.svg', width=2.8).set_color(WHITE_G), TexGen(r'THE\\FOUNDATIONS\\OF\\GEOMETRY\\~\\by\\David Hilbert', font_sz=26, col=INK_G).shift(0.3*UP))
       
        edge = SVGMobject('edge.svg').set_color(YELL_G).set_stroke(YELL_G).stretch_to_fit_height(6).stretch_to_fit_width(1).rotate(-PI/2)
        
        # ANIMATE
        self.wait()
        play_intro()
        play_def_in()
        play_def_1()
        play_def_2_4()
        play_def_5_7()
        play_def_8_12()
        play_def_13_14()
        play_def_15_18()
        play_def_19()
        play_def_20_21()
        play_def_22()
        play_def_23()
        play_axs()
        play_ax_1() #MovingCameraScene
        play_ax_2_4()
        play_ax_5() #MovingCameraScene
        play_tube()
        play_commns()
        play_props()
        play_prop_1()
        play_end()
        self.wait()
